import { create } from 'zustand';
import { db } from '../db/db';
import { generateUUID } from '../lib/utils';
import { useSettingsStore, getActivePromptIndices } from './settings.store';
import { encryptData, decryptData } from '../lib/crypto';
import { WebDAVClient } from '../lib/webdav';
import { OneDriveClient, GDriveClient, DropboxClient } from '../lib/cloudClients';
import { 
  startOfWeek, 
  endOfWeek, 
  startOfMonth, 
  endOfMonth, 
  startOfQuarter, 
  endOfQuarter,
  startOfDay,
  endOfDay,
  parseISO,
  isWithinInterval,
  format
} from 'date-fns';

export interface SearchItem {
  id: string;
  type: 'record' | 'diary' | 'review' | 'insight';
  title: string;
  content: string;
  date: string;
  highlightSnippets: string;
}

interface AppState {
  isProcessingDiary: boolean;
  isProcessingReviewMap: Record<string, boolean>;
  diaryErrorMap: Record<string, string>;
  isSilentlyGenerating: boolean;
  isSilentlyGeneratingReview: boolean;
  batchProgress: { current: number; total: number; type: 'diary' | 'review' } | null;
  autoGeneratedNotification: { date: string; diaryId: string } | null;
  autoGeneratedReviewNotification: { date: string; reviewId: string } | null;
  
  // 搜索状态
  isSearchMode: boolean;
  searchQuery: string;
  searchHistory: string[];
  searchFilters: { 
    dateRange: string; 
    modules: string[]; 
    customStartDate?: string; 
    customEndDate?: string; 
  };
  searchResults: SearchItem[];

  // 云同步状态
  syncStatus: 'idle' | 'syncing' | 'error' | 'disabled';
  syncErrorMessage: string;

  syncNow: () => Promise<void>;
  setSyncStatus: (status: 'idle' | 'syncing' | 'error' | 'disabled', errorMsg?: string) => void;

  generateDiaryTimeline: (dateStr: string, logs: any[], idToOverwrite?: string, targetPromptIndex?: number) => Promise<void>;
  generateReview: (tempId: string, dateStr: string, logs: any[], diaryContent: string, targetPromptIndex?: number) => Promise<void>;
  clearDiaryError: (dateStr: string) => void;
  silentlyGenerateDiary: (dateStr: string, logs: any[]) => Promise<void>;
  silentlyGenerateReview: (dateStr: string, logs: any[]) => Promise<void>;
  clearAutoGeneratedNotification: () => void;
  clearAutoGeneratedReviewNotification: () => void;
  generateAllDiaries: (dateStr: string, logs: any[]) => Promise<void>;
  generateAllReviews: (dateStr: string, logs: any[]) => Promise<void>;

  // 搜索动作
  setSearchMode: (open: boolean) => void;
  setSearchQuery: (query: string) => void;
  setSearchFilters: (filters: { 
    dateRange: string; 
    modules: string[]; 
    customStartDate?: string; 
    customEndDate?: string; 
  }) => void;
  clearSearchHistory: () => void;
  executeSearch: () => Promise<void>;
  addSearchHistory: (query: string) => void;
}

export const useAppStore = create<AppState>((set, get) => ({
  isProcessingDiary: false,
  isProcessingReviewMap: {},
  diaryErrorMap: {},
  isSilentlyGenerating: false,
  isSilentlyGeneratingReview: false,
  batchProgress: null,
  autoGeneratedNotification: null,
  autoGeneratedReviewNotification: null,

  // 云同步状态
  syncStatus: 'disabled',
  syncErrorMessage: '',

  // 搜索初始化状态
  isSearchMode: false,
  searchQuery: '',
  searchHistory: (() => {
    try {
      return JSON.parse(localStorage.getItem('baimiao_search_history') || '[]');
    } catch {
      return [];
    }
  })(),
  searchFilters: { 
    dateRange: '全部', 
    modules: ['record', 'diary', 'review', 'insight'],
    customStartDate: '',
    customEndDate: ''
  },
  searchResults: [],

  clearDiaryError: (dateStr) => {
    set((state) => {
      const newMap = { ...state.diaryErrorMap };
      delete newMap[dateStr];
      return { diaryErrorMap: newMap };
    });
  },

  generateDiaryTimeline: async (dateStr, logs, idToOverwrite, targetPromptIndex) => {
    if (!logs || logs.length === 0) return;
    
    set({ isProcessingDiary: true });
    get().clearDiaryError(dateStr);
    
    const settings = { ...useSettingsStore.getState() };
    const promptNames = ['默认', '自定义 1', '自定义 2', '自定义 3'];
    
    // Determine active prompt index.
    // 优先使用显式传入的 targetPromptIndex，否则尝试使用待覆盖的原本日记的 Prompt 配置，最后采用全局默认的。
    let activePromptIndex = targetPromptIndex !== undefined 
      ? targetPromptIndex 
      : (settings.diaryPromptIndex ?? 0);
      
    if (idToOverwrite && targetPromptIndex === undefined) {
      const originalDiary = await db.daily_diaries.get(idToOverwrite);
      if (originalDiary && originalDiary.prompt_index !== undefined) {
        activePromptIndex = originalDiary.prompt_index;
      }
    }
    
    let activePromptName = promptNames[activePromptIndex];
    settings.diaryPromptIndex = activePromptIndex;
    if (settings.diaryPrompts && settings.diaryPrompts[activePromptIndex] !== undefined) {
      settings.diaryPrompt = settings.diaryPrompts[activePromptIndex];
    }
    
    try {
      const response = await fetch('/api/generate-timeline', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          date: dateStr,
          timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
          logs: logs.map(l => ({ id: l.id, content: l.content, created_at: l.created_at })),
          settings
        })
      });
      
      if (!response.ok) {
         const errText = await response.text();
         let errData = { error: errText };
         try { errData = JSON.parse(errText); } catch(e){}
         throw new Error(errData.error || 'AI 服务响应异常，请重试');
      }
      
      const data = await response.json();
      
      // Store the ai_summary inside the timeline_json array for the summary display
      const timelineContent = JSON.stringify([{ summary: data.ai_summary || "暂无内容概要" }]);

      if (idToOverwrite) {
        await db.daily_diaries.update(idToOverwrite, {
           timeline_json: timelineContent,
           raw_log_ids: logs.map(l => l.id),
           ai_editorial: data.ai_editorial,
           ai_review: data.ai_review,
           prompt_index: activePromptIndex,
           prompt_name: activePromptName,
           updated_at: Date.now()
        });
      } else {
        await db.daily_diaries.add({
           id: generateUUID(),
           diary_date: dateStr,
           raw_log_ids: logs.map(l => l.id),
           timeline_json: timelineContent,
           ai_editorial: data.ai_editorial,
           ai_review: data.ai_review,
           updated_at: Date.now(),
           prompt_index: activePromptIndex,
           prompt_name: activePromptName
        });
      }
    } catch (err: any) {
      console.error("Timeline Generation Error:", err);
      set((state) => ({
        diaryErrorMap: {
          ...state.diaryErrorMap,
          [dateStr]: err.message || "生成时间轴失败，请检查网络连接"
        }
      }));
    } finally {
      set({ isProcessingDiary: false });
    }
  },

  generateReview: async (tempId, dateStr, logs, diaryContent, targetPromptIndex) => {
    if (!logs || logs.length === 0) return;
    
    set((state) => ({
      isProcessingReviewMap: { ...state.isProcessingReviewMap, [tempId]: true }
    }));
    get().clearDiaryError(dateStr);
    
    const settings = { ...useSettingsStore.getState() };
    const promptNames = ['默认', '自定义 1', '自定义 2', '自定义 3'];
    
    // Determine active prompt index
    const activePromptIndex = targetPromptIndex !== undefined
      ? targetPromptIndex
      : (settings.reviewPromptIndex ?? 0);
    
    const activePromptName = promptNames[activePromptIndex];
    settings.reviewPromptIndex = activePromptIndex;
    if (settings.reviewPrompts && settings.reviewPrompts[activePromptIndex] !== undefined) {
      settings.reviewPrompt = settings.reviewPrompts[activePromptIndex];
    }
    
    try {
      const response = await fetch('/api/generate-review', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          date: dateStr,
          timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
          logs: logs.map(l => ({ id: l.id, content: l.content, created_at: l.created_at })),
          diaryContent,
          settings
        })
      });
      
      if (!response.ok) {
         const errText = await response.text();
         let errData = { error: errText };
         try { errData = JSON.parse(errText); } catch(e){}
         throw new Error(errData.error || 'AI 服务响应异常，请重试');
      }
      
      const data = await response.json();
      
      // Always write to the independent daily_reviews table — never touch daily_diaries
      await db.daily_reviews.add({
        id: generateUUID(),
        review_date: dateStr,
        raw_log_ids: logs.map(l => l.id),
        ai_review: data.ai_review || '',
        ai_summary: data.ai_summary || '暂无内容概要',
        review_prompt_index: activePromptIndex,
        review_prompt_name: activePromptName,
        updated_at: Date.now(),
      });
    } catch (err: any) {
      console.error("Review Generation Error:", err);
      set((state) => ({
        diaryErrorMap: {
          ...state.diaryErrorMap,
          [dateStr]: err.message || "生成回顾失败，请检查网络连接"
        }
      }));
    } finally {
      set((state) => ({
        isProcessingReviewMap: { ...state.isProcessingReviewMap, [tempId]: false }
      }));
    }
  },

  clearAutoGeneratedNotification: () => {
    set({ autoGeneratedNotification: null });
  },

  clearAutoGeneratedReviewNotification: () => {
    set({ autoGeneratedReviewNotification: null });
  },

  silentlyGenerateDiary: async (dateStr, logs) => {
    if (!logs || logs.length === 0) return;
    if (get().isSilentlyGenerating) return;
    
    set({ isSilentlyGenerating: true });
    
    const settings = { ...useSettingsStore.getState() };
    const indices = getActivePromptIndices(settings.diaryPrompts || []);
    const promptNames = ['默认', '自定义 1', '自定义 2', '自定义 3'];
    
    try {
      let lastDiaryId = null;
      for (let i = 0; i < indices.length; i++) {
        const activePromptIndex = indices[i];
        const activePromptName = promptNames[activePromptIndex];
        
        if (i > 0) {
          await new Promise(r => setTimeout(r, 3000));
        }

        settings.diaryPromptIndex = activePromptIndex;
        if (settings.diaryPrompts && settings.diaryPrompts[activePromptIndex] !== undefined) {
          settings.diaryPrompt = settings.diaryPrompts[activePromptIndex];
        } else {
          settings.diaryPrompt = undefined;
        }
        
        const response = await fetch('/api/generate-timeline', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            date: dateStr,
            timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
            logs: logs.map(l => ({ id: l.id, content: l.content, created_at: l.created_at })),
            settings
          })
        });
        
        if (!response.ok) {
          throw new Error(`AI 服务响应异常 (Prompt: ${activePromptName})`);
        }
        
        const data = await response.json();
        const timelineContent = JSON.stringify([{ summary: data.ai_summary || "暂无内容概要" }]);
        const diaryId = generateUUID();

        await db.daily_diaries.add({
          id: diaryId,
          diary_date: dateStr,
          raw_log_ids: logs.map(l => l.id),
          timeline_json: timelineContent,
          ai_editorial: data.ai_editorial,
          ai_review: data.ai_review,
          updated_at: Date.now(),
          prompt_index: activePromptIndex,
          prompt_name: activePromptName
        });
        
        lastDiaryId = diaryId;
      }

      if (lastDiaryId) {
        set({
          autoGeneratedNotification: {
            date: dateStr,
            diaryId: lastDiaryId
          }
        });
      }
    } catch (err: any) {
      console.error("Silent Timeline Generation Error:", err);
    } finally {
      set({ isSilentlyGenerating: false });
    }
  },

  silentlyGenerateReview: async (dateStr, logs) => {
    if (!logs || logs.length === 0) return;
    if (get().isSilentlyGeneratingReview) return;
    
    set({ isSilentlyGeneratingReview: true });
    
    const settings = { ...useSettingsStore.getState() };
    const indices = getActivePromptIndices(settings.reviewPrompts || []);
    const promptNames = ['默认', '自定义 1', '自定义 2', '自定义 3'];
    
    try {
      let lastReviewId = null;
      for (let i = 0; i < indices.length; i++) {
        const activePromptIndex = indices[i];
        const activePromptName = promptNames[activePromptIndex];

        if (i > 0) {
          await new Promise(r => setTimeout(r, 3000));
        }

        settings.reviewPromptIndex = activePromptIndex;
        if (settings.reviewPrompts && settings.reviewPrompts[activePromptIndex] !== undefined) {
          settings.reviewPrompt = settings.reviewPrompts[activePromptIndex];
        } else {
          settings.reviewPrompt = undefined;
        }
        
        const response = await fetch('/api/generate-review', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            date: dateStr,
            timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
            logs: logs.map(l => ({ id: l.id, content: l.content, created_at: l.created_at })),
            diaryContent: '',
            settings
          })
        });
        
        if (!response.ok) {
          throw new Error(`AI 服务响应异常 (Prompt: ${activePromptName})`);
        }
        
        const data = await response.json();
        const reviewId = generateUUID();

        await db.daily_reviews.add({
          id: reviewId,
          review_date: dateStr,
          raw_log_ids: logs.map(l => l.id),
          ai_review: data.ai_review || '',
          ai_summary: data.ai_summary || '暂无内容概要',
          review_prompt_index: activePromptIndex,
          review_prompt_name: activePromptName,
          updated_at: Date.now(),
        });

        lastReviewId = reviewId;
      }

      if (lastReviewId) {
        set({
          autoGeneratedReviewNotification: {
            date: dateStr,
            reviewId: lastReviewId
          }
        });
      }
    } catch (err: any) {
      console.error("Silent Review Generation Error:", err);
    } finally {
      set({ isSilentlyGeneratingReview: false });
    }
  },

  generateAllDiaries: async (dateStr, logs) => {
    if (!logs || logs.length === 0) return;
    const settings = useSettingsStore.getState();
    const indices = getActivePromptIndices(settings.diaryPrompts);
    if (indices.length === 0) return;

    const total = indices.length;
    for (let i = 0; i < indices.length; i++) {
      set({ batchProgress: { current: i + 1, total, type: 'diary' } });
      if (i > 0) {
        await new Promise(r => setTimeout(r, 3000));
      }
      try {
        await get().generateDiaryTimeline(dateStr, logs, undefined, indices[i]);
      } catch (err) {
        console.error(`Batch diary generation failed for prompt index ${indices[i]}:`, err);
      }
    }
    set({ batchProgress: null });
  },

  generateAllReviews: async (dateStr, logs) => {
    if (!logs || logs.length === 0) return;
    const settings = useSettingsStore.getState();
    const indices = getActivePromptIndices(settings.reviewPrompts);
    if (indices.length === 0) return;

    const total = indices.length;
    for (let i = 0; i < indices.length; i++) {
      set({ batchProgress: { current: i + 1, total, type: 'review' } });
      if (i > 0) {
        await new Promise(r => setTimeout(r, 3000));
      }
      try {
        const tempId = generateUUID();
        await get().generateReview(tempId, dateStr, logs, '', indices[i]);
      } catch (err) {
        console.error(`Batch review generation failed for prompt index ${indices[i]}:`, err);
      }
    }
    set({ batchProgress: null });
  },

  setSearchMode: (open) => {
    set({ isSearchMode: open });
    if (!open) {
      set({ searchQuery: '', searchResults: [] });
    }
  },

  setSearchQuery: (query) => {
    set({ searchQuery: query });
    get().executeSearch();
  },

  setSearchFilters: (filters) => {
    set({ searchFilters: filters });
    get().executeSearch();
  },

  clearSearchHistory: () => {
    localStorage.removeItem('baimiao_search_history');
    set({ searchHistory: [] });
  },

  executeSearch: async () => {
    const { searchQuery, searchFilters } = get();
    if (!searchQuery.trim()) {
      set({ searchResults: [] });
      return;
    }

    const query = searchQuery.trim();
    const { dateRange, modules, customStartDate, customEndDate } = searchFilters;
    const results: SearchItem[] = [];

    // 1. 碎屑记录搜索
    if (modules.includes('record')) {
      const logs = await db.raw_logs.toArray();
      const matchedLogs = logs.filter(log => {
        const matchesQuery = log.content.toLowerCase().includes(query.toLowerCase());
        const matchesDate = isDateInFilter(log.created_at, dateRange, customStartDate, customEndDate);
        return matchesQuery && matchesDate;
      });

      results.push(...matchedLogs.map(log => ({
        id: log.id,
        type: 'record' as const,
        title: `碎屑记录 · ${format(new Date(log.created_at), 'yyyy-MM-dd HH:mm')}`,
        content: log.content,
        date: format(new Date(log.created_at), 'yyyy-MM-dd'),
        highlightSnippets: getHighlightSnippet(log.content, query)
      })));
    }

    // 2. 日记搜索
    const showDiary = modules.includes('diary');
    const showReview = modules.includes('review');
    if (showDiary) {
      const diaries = await db.daily_diaries.toArray();
      const matchedDiaries = diaries.filter(d => {
        const diaryDateObj = parseISO(d.diary_date);
        return isDateInFilter(diaryDateObj, dateRange, customStartDate, customEndDate);
      });

      matchedDiaries.forEach(d => {
        if (d.ai_editorial && d.ai_editorial.toLowerCase().includes(query.toLowerCase())) {
          results.push({
            id: d.id,
            type: 'diary' as const,
            title: `整合日记 · ${d.diary_date}`,
            content: d.ai_editorial,
            date: d.diary_date,
            highlightSnippets: getHighlightSnippet(d.ai_editorial, query)
          });
        }
      });
    }

    // 3. 回顾搜索（独立 daily_reviews 表）
    if (showReview) {
      const reviews = await db.daily_reviews.toArray();
      const matchedReviews = reviews.filter(r => {
        const reviewDateObj = parseISO(r.review_date);
        return isDateInFilter(reviewDateObj, dateRange, customStartDate, customEndDate)
          && r.ai_review && r.ai_review.toLowerCase().includes(query.toLowerCase());
      });

      matchedReviews.forEach(r => {
        results.push({
          id: r.id,
          type: 'review' as const,
          title: `反思回顾 · ${r.review_date}`,
          content: r.ai_review,
          date: r.review_date,
          highlightSnippets: getHighlightSnippet(r.ai_review, query)
        });
      });
    }

    // 3. 洞察搜索
    if (modules.includes('insight')) {
      const insights = await db.insights.toArray();
      const matchedInsights = insights.filter(ins => {
        const matchesQuery = ins.content.toLowerCase().includes(query.toLowerCase());
        const matchesDate = isDateInFilter(ins.created_at, dateRange, customStartDate, customEndDate);
        return matchesQuery && matchesDate;
      });

      results.push(...matchedInsights.map(ins => ({
        id: ins.id || generateUUID(),
        type: 'insight' as const,
        title: `生命洞察 · ${ins.range_label}`,
        content: ins.content,
        date: ins.start_date,
        highlightSnippets: getHighlightSnippet(ins.content, query)
      })));
    }

    // 按日期倒序排列
    results.sort((a, b) => b.date.localeCompare(a.date));
    set({ searchResults: results });
  },

  addSearchHistory: (query) => {
    if (!query || !query.trim()) return;
    const trimmed = query.trim();
    set(state => {
      const newHistory = [trimmed, ...state.searchHistory.filter(h => h !== trimmed)].slice(0, 10);
      localStorage.setItem('baimiao_search_history', JSON.stringify(newHistory));
      return { searchHistory: newHistory };
    });
  },

  setSyncStatus: (status, errorMsg) => set({ syncStatus: status, syncErrorMessage: errorMsg || '' }),

  syncNow: async () => {
    const settings = useSettingsStore.getState();
    if (!settings.syncEnabled) {
      set({ syncStatus: 'disabled', syncErrorMessage: '' });
      return;
    }

    // 1. 根据不同服务商做针对性的配置校验
    if (settings.syncProvider === 'webdav') {
      if (!settings.syncEndpoint || !settings.syncUsername || !settings.syncPassword || !settings.syncPasswordE2EE) {
        set({ syncStatus: 'error', syncErrorMessage: 'WebDAV 云同步配置不完整，请检查设置。' });
        return;
      }
    } else if (settings.syncProvider === 'onedrive') {
      if (!settings.syncOneDriveToken || !settings.syncPasswordE2EE) {
        set({ syncStatus: 'error', syncErrorMessage: 'OneDrive 尚未授权，或端到端加密密码未配置。' });
        return;
      }
    } else if (settings.syncProvider === 'gdrive') {
      if (!settings.syncGDriveToken || !settings.syncPasswordE2EE) {
        set({ syncStatus: 'error', syncErrorMessage: 'Google Drive 尚未授权，或端到端加密密码未配置。' });
        return;
      }
    } else if (settings.syncProvider === 'dropbox') {
      if (!settings.syncDropboxToken || !settings.syncPasswordE2EE) {
        set({ syncStatus: 'error', syncErrorMessage: 'Dropbox 尚未授权，或端到端加密密码未配置。' });
        return;
      }
    } else {
      set({ syncStatus: 'error', syncErrorMessage: '未知的云同步服务商。' });
      return;
    }

    set({ syncStatus: 'syncing', syncErrorMessage: '' });

    try {
      let client: any;
      if (settings.syncProvider === 'webdav') {
        client = new WebDAVClient(settings.syncEndpoint, settings.syncUsername, settings.syncPassword);
      } else if (settings.syncProvider === 'onedrive') {
        client = new OneDriveClient(settings.syncOneDriveToken || '');
      } else if (settings.syncProvider === 'gdrive') {
        client = new GDriveClient(settings.syncGDriveToken || '');
      } else if (settings.syncProvider === 'dropbox') {
        client = new DropboxClient(settings.syncDropboxToken || '');
      }
      
      // 1. 确保云端目录存在
      const dirExists = await client.checkDir(settings.syncDirectory);
      if (!dirExists) {
        await client.createDir(settings.syncDirectory);
      }

      // 2. 尝试从云端拉取已有的加密备份
      const syncFilePath = `${settings.syncDirectory}data.enc`;
      let cloudData: any = null;
      try {
        const encryptedBuffer = await client.getFile(syncFilePath);
        const decryptedText = await decryptData(encryptedBuffer, settings.syncPasswordE2EE);
        cloudData = JSON.parse(decryptedText);
      } catch (err: any) {
        if (err.message !== 'FILE_NOT_FOUND') {
          throw err; 
        }
      }

      // 3. 收集本地数据
      const localLogs = await db.raw_logs.toArray();
      const localDiaries = await db.daily_diaries.toArray();
      const localReviews = await db.daily_reviews.toArray();
      const localInsights = await db.insights.toArray();

      // 4. 数据合并 (双向合并以本地 IndexedDB 为基准，并合并云端)
      if (cloudData && cloudData.version === 1) {
        // 合并 logs
        if (cloudData.logs && Array.isArray(cloudData.logs)) {
          for (const cLog of cloudData.logs) {
            const exist = await db.raw_logs.get(cLog.id);
            if (!exist) {
              if (cLog.audioDataUrl) {
                try {
                  const res = await fetch(cLog.audioDataUrl);
                  cLog.audioBlob = await res.blob();
                } catch(e) {
                  console.error("Failed to restore audioBlob, keeping text", e);
                }
                delete cLog.audioDataUrl;
              }
              await db.raw_logs.add(cLog);
            }
          }
        }
        // 合并 diaries
        if (cloudData.diaries && Array.isArray(cloudData.diaries)) {
          for (const cDiary of cloudData.diaries) {
            const exist = await db.daily_diaries.get(cDiary.id);
            if (!exist) {
              await db.daily_diaries.add(cDiary);
            } else if (cDiary.updated_at > exist.updated_at) {
              await db.daily_diaries.put(cDiary);
            }
          }
        }
        // 合并 reviews
        if (cloudData.reviews && Array.isArray(cloudData.reviews)) {
          for (const cReview of cloudData.reviews) {
            const exist = await db.daily_reviews.get(cReview.id);
            if (!exist) {
              await db.daily_reviews.add(cReview);
            } else if (cReview.updated_at > exist.updated_at) {
              await db.daily_reviews.put(cReview);
            }
          }
        }
        // 合并 insights
        if (cloudData.insights && Array.isArray(cloudData.insights)) {
          for (const cInsight of cloudData.insights) {
            const exist = await db.insights.get(cInsight.id);
            if (!exist) {
              await db.insights.add(cInsight);
            } else if (cInsight.created_at > exist.created_at) {
              await db.insights.put(cInsight);
            }
          }
        }
      }

      // 5. 重新读取合并后的最新本地数据，并加密上传到云端
      const mergedLogs = await db.raw_logs.toArray();
      const mergedDiaries = await db.daily_diaries.toArray();
      const mergedReviews = await db.daily_reviews.toArray();
      const mergedInsights = await db.insights.toArray();

      const packedMergedLogs = await Promise.all(mergedLogs.map(async l => {
        if (l.audioBlob) {
          const dataUrl = await new Promise<string>((resolve, reject) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve(reader.result as string);
            reader.onerror = reject;
            reader.readAsDataURL(l.audioBlob!);
          });
          return { ...l, audioBlob: undefined, audioDataUrl: dataUrl };
        }
        return l;
      }));

      const exportPayload = {
        "version": 1,
        exported_at: Date.now(),
        logs: packedMergedLogs,
        diaries: mergedDiaries,
        reviews: mergedReviews,
        insights: mergedInsights
      };

      const payloadJson = JSON.stringify(exportPayload);
      const encryptedBuffer = await encryptData(payloadJson, settings.syncPasswordE2EE);
      
      await client.putFile(syncFilePath, encryptedBuffer);

      // 6. 更新成功状态
      settings.setSettings({ syncLastTime: Date.now() });
      set({ syncStatus: 'idle', syncErrorMessage: '' });
    } catch (err: any) {
      console.error("Sync process failed:", err);
      set({ 
        syncStatus: 'error', 
        syncErrorMessage: err.message || "连接网盘或加密失败" 
      });
    }
  }
}));

// === 搜索辅助函数 ===
const isDateInFilter = (
  date: Date | number, 
  range: string, 
  customStartDate?: string, 
  customEndDate?: string
): boolean => {
  if (range === '全部') return true;
  const now = new Date();
  const target = typeof date === 'number' ? new Date(date) : date;
  
  let start: Date;
  let end: Date;

  if (range === '本周') {
    start = startOfWeek(now, { weekStartsOn: 1 });
    end = endOfWeek(now, { weekStartsOn: 1 });
  } else if (range === '本月') {
    start = startOfMonth(now);
    end = endOfMonth(now);
  } else if (range === '本季度') {
    start = startOfQuarter(now);
    end = endOfQuarter(now);
  } else if (range === '自定义') {
    if (!customStartDate && !customEndDate) return true;
    
    const startObj = customStartDate ? startOfDay(parseISO(customStartDate)) : new Date(0);
    const endObj = customEndDate ? endOfDay(parseISO(customEndDate)) : new Date(8640000000000000);

    return isWithinInterval(target, { start: startObj, end: endObj });
  } else {
    return true;
  }

  return isWithinInterval(target, { start, end });
};

const escapeRegExp = (str: string) => {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
};

const getHighlightSnippet = (text: string, query: string): string => {
  if (!text) return '';
  const cleanText = text.replace(/[\r\n]+/g, ' '); // 扁平化多行文本
  const index = cleanText.toLowerCase().indexOf(query.toLowerCase());
  
  if (index === -1) {
    return cleanText.slice(0, 80) + (cleanText.length > 80 ? '...' : '');
  }
  
  const start = Math.max(0, index - 20);
  const end = Math.min(cleanText.length, index + query.length + 40);
  let snippet = cleanText.slice(start, end);
  
  if (start > 0) snippet = '...' + snippet;
  if (end < cleanText.length) snippet = snippet + '...';
  
  const escapedQuery = escapeRegExp(query);
  const regex = new RegExp(`(${escapedQuery})`, 'gi');
  return snippet.replace(regex, '<mark class="bg-amber-100 text-amber-900 rounded-[3px] px-0.5 font-medium">$1</mark>');
};

// === Dexie Mutation Hooks for Auto-Sync ===
let autoSyncTimer: any = null;

const triggerAutoSync = () => {
  const appStore = useAppStore.getState();
  if (appStore.syncStatus === 'syncing') {
    return; // Ignore database mutations generated during alignment sync process
  }
  const settings = useSettingsStore.getState();
  if (settings.syncEnabled && settings.syncAutoChange) {
    if (autoSyncTimer) clearTimeout(autoSyncTimer);
    autoSyncTimer = setTimeout(() => {
      if (useAppStore.getState().syncStatus !== 'syncing') {
        useAppStore.getState().syncNow();
      }
    }, 2000); // 2s debounce window
  }
};

db.raw_logs.hook('creating', () => { triggerAutoSync(); });
db.raw_logs.hook('updating', () => { triggerAutoSync(); });
db.raw_logs.hook('deleting', () => { triggerAutoSync(); });

db.daily_diaries.hook('creating', () => { triggerAutoSync(); });
db.daily_diaries.hook('updating', () => { triggerAutoSync(); });
db.daily_diaries.hook('deleting', () => { triggerAutoSync(); });

db.daily_reviews.hook('creating', () => { triggerAutoSync(); });
db.daily_reviews.hook('updating', () => { triggerAutoSync(); });
db.daily_reviews.hook('deleting', () => { triggerAutoSync(); });

db.insights.hook('creating', () => { triggerAutoSync(); });
db.insights.hook('updating', () => { triggerAutoSync(); });
db.insights.hook('deleting', () => { triggerAutoSync(); });