import { create } from 'zustand';
import { db, normalizeLegacyDiary, normalizeLegacyReview, normalizeLegacyInsight } from '../db/db';
import { generateUUID } from '../lib/utils';
import { SYNC_CONSTANTS } from '../config/constants';
import { useSettingsStore, isDiarySlot, getEntryTypeForSlot, getLegacyPromptIndices } from './settings.store';
import type { ToastItem, ToastType } from '../components/Toast';
import { cosineSimilarity, requestEmbedding, getEmbedSettings, registerQueueChangeListener } from '../lib/embedding';
import { computeCosineBatch, type CosineCandidate, type CosineScore } from '../lib/cosineWorker';
import { encryptData, decryptData } from '../lib/crypto';
import { WebDAVClient } from '../lib/webdav';
import { OneDriveClient, GDriveClient, DropboxClient } from '../lib/cloudClients';
import { 
  startOfWeek, 
  endOfWeek, 
  startOfMonth, 
  endOfMonth, 
  startOfQuarter, 
  endOfQuarter,
  startOfDay,
  endOfDay,
  parseISO,
  isWithinInterval,
  format,
  subDays
} from 'date-fns';
import { parseTagsFromText, resolveAlias, matchesByPrefix, normalizeTagPath } from '../lib/tags';
import { useTagsStore } from './tags.store';

// #31 AI 生成的回顾/日记自动打全局标签：解析 AI 文本中的 #标签，经别名纠正后落库，返回去重后的标签路径数组。
async function processTagsForContent(text: string): Promise<string[]> {
  if (!text) return [];
  const { refreshAliases, createTag } = useTagsStore.getState();
  await refreshAliases();
  const aliases = useTagsStore.getState().aliases;
  const rawTags = parseTagsFromText(text);
  if (rawTags.length === 0) return [];
  const resolved = rawTags.map(t => resolveAlias(t, aliases));
  const unique = Array.from(new Set(resolved));
  for (const tag of unique) {
    await createTag(tag);
  }
  return unique;
}

export interface SearchItem {
  id: string;
  type: 'record' | 'diary' | 'review' | 'insight';
  title: string;
  content: string;
  date: string;
  highlightSnippets: string;
}

export interface AutoGenTask {
  id: string;
  dateStr: string;
  // #5: 合并后所有任务 type 统一为 'review'，由 promptIndex 决定调用哪个 API
  type: 'review';
  promptIndex: number;
  status: 'pending' | 'processing' | 'failed';
  retryCount: number;
}

// NOTE: AutoGenTask 当前为「按日 + 按槽位」的日记/回顾自动队列结构（dateStr + promptIndex）。
// 明悟/洞察（mingwu）生成是「按时间范围」（rangeType/startTime/endTime/rangeLabel），
// 与本队列结构不兼容，本次未扩展自动队列。明悟/洞察仍由 useMingwuStore.generateMingwu
// 手动触发，并已接入 mingwuInsightSelectedIndices 按选中类型过滤落库（US36）。

interface AppState {
  isProcessingDiary: boolean;
  isProcessingReviewMap: Record<string, boolean>;
  diaryErrorMap: Record<string, string>;
  isSilentlyGenerating: boolean;
  isSilentlyGeneratingReview: boolean;
  // #5: batchProgress.type 统一为 'review'（日记+回顾已合并）
  batchProgress: { current: number; total: number; type: 'review' } | null;
  autoGeneratedNotification: { date: string; diaryId: string } | null;
  autoGeneratedReviewNotification: { date: string; reviewId: string } | null;

  // #8 明悟生成队列状态（手动按时间范围生成，非每日自动队列）
  isGeneratingMingwu: boolean;
  mingwuError: string;
  clearMingwuError: () => void;

  // 全局 Toast 提示
  toasts: ToastItem[];
  addToast: (message: string, type?: ToastType) => void;
  removeToast: (id: string) => void;

  // 任务队列状态
  autoGenTasks: AutoGenTask[];
  isProcessingQueue: boolean;
  isQueuePaused: boolean;
  
  // 搜索状态
  isSearchMode: boolean;
  isCopilotMode: boolean;
  isRandomWalkMode: boolean;

  // 需求 6：沉思视图模式 & 明悟时间范围（顶部栏胶囊与页面共享状态）
  thoughtsViewMode: 'masonry' | 'timeline';
  setThoughtsViewMode: (mode: 'masonry' | 'timeline') => void;
  mingwuTimeRange: string;
  setMingwuTimeRange: (range: string) => void;
  mingwuCustomStart: string;
  setMingwuCustomStart: (date: string) => void;
  mingwuCustomEnd: string;
  setMingwuCustomEnd: (date: string) => void;

  searchQuery: string;
  searchHistory: string[];
  searchFilters: {
    dateRange: string;
    modules: string[];
    customStartDate?: string;
    customEndDate?: string;
    diaryPromptIndex?: number; // when set, diary semantic search filters to this prompt_index only
  };
  searchResults: SearchItem[];
  semanticSearchEnabled: boolean;
  isSearching: boolean;
  searchError: string | null;
  totalVectorsCount: number;
  embeddingQueueSize: number;

  // 云同步状态
  syncStatus: 'idle' | 'syncing' | 'error' | 'disabled' | 'credentials_missing';
  syncErrorMessage: string;

  syncNow: (forcePolicy?: 'local_wins' | 'cloud_wins' | 'merge') => Promise<void>;
  setSyncStatus: (status: 'idle' | 'syncing' | 'error' | 'disabled' | 'credentials_missing', errorMsg?: string) => void;

  generateDiaryTimeline: (dateStr: string, logs: any[], idToOverwrite?: string, targetPromptIndex?: number) => Promise<void>;
  generateReview: (tempId: string, dateStr: string, logs: any[], diaryContent: string, targetPromptIndex?: number) => Promise<void>;
  clearDiaryError: (dateStr: string) => void;
  // #5: silentlyGenerateDiary/silentlyGenerateReview 保留签名但内部走统一 5 槽逻辑
  silentlyGenerateDiary: (dateStr: string, logs: any[]) => Promise<void>;
  silentlyGenerateReview: (dateStr: string, logs: any[]) => Promise<void>;
  clearAutoGeneratedNotification: () => void;
  clearAutoGeneratedReviewNotification: () => void;
  // #5: generateAllDiaries/generateAllReviews 保留签名但内部走统一 5 槽逻辑
  generateAllDiaries: (dateStr: string, logs: any[]) => Promise<void>;
  generateAllReviews: (dateStr: string, logs: any[]) => Promise<void>;
  // #5: 新增 - 根据选中槽位批量生成（多选浮层「生成 N 篇回顾」按钮调用）
  generateSelected: (dateStr: string, logs: any[], selectedIndices: number[]) => Promise<void>;

  // 任务队列动作
  initQueue: () => void;
  checkAndGenerateHistoryTasks: (daysLimit?: number) => Promise<void>;
  processNextQueueTask: () => Promise<void>;
  clearQueue: () => void;
  setQueuePaused: (paused: boolean) => void;

  // 搜索动作
  setSearchMode: (open: boolean) => void;
  setCopilotMode: (open: boolean) => void;
  setRandomWalkMode: (open: boolean) => void;
  setSearchQuery: (query: string) => void;
  setSearchFilters: (filters: {
    dateRange: string;
    modules: string[];
    customStartDate?: string;
    customEndDate?: string;
    diaryPromptIndex?: number;
  }) => void;
  clearSearchHistory: () => void;
  executeSearch: () => Promise<void>;
  addSearchHistory: (query: string) => void;
  setSemanticSearchEnabled: (enabled: boolean) => void;
  updateVectorsCount: () => Promise<void>;
}

export const useAppStore = create<AppState>((set, get) => ({
  isProcessingDiary: false,
  isProcessingReviewMap: {},
  diaryErrorMap: {},
  isSilentlyGenerating: false,
  isSilentlyGeneratingReview: false,
  batchProgress: null,
  autoGeneratedNotification: null,
  autoGeneratedReviewNotification: null,

  // #8 明悟生成状态
  isGeneratingMingwu: false,
  mingwuError: '',

  toasts: [],

  autoGenTasks: (() => {
    try {
      return JSON.parse(localStorage.getItem('baimiao_autogen_tasks') || '[]');
    } catch {
      return [];
    }
  })(),
  isProcessingQueue: false,
  isQueuePaused: false,

  // 云同步状态
  syncStatus: 'disabled',
  syncErrorMessage: '',

  // 搜索初始化状态
  isSearchMode: false,
  isCopilotMode: false,
  isRandomWalkMode: false,

  // 需求 6：沉思视图模式 & 明悟时间范围（顶部栏胶囊与页面共享状态）
  thoughtsViewMode: 'masonry',
  mingwuTimeRange: 'week',
  mingwuCustomStart: '',
  mingwuCustomEnd: '',

  searchQuery: '',
  searchHistory: (() => {
    try {
      return JSON.parse(localStorage.getItem('baimiao_search_history') || '[]');
    } catch {
      return [];
    }
  })(),
  searchFilters: { 
    dateRange: '全部', 
    modules: ['record', 'diary', 'review', 'insight'],
    customStartDate: '',
    customEndDate: ''
  },
  searchResults: [],
  semanticSearchEnabled: false,
  isSearching: false,
  searchError: null,
  totalVectorsCount: 0,
  embeddingQueueSize: (() => {
    try {
      return JSON.parse(localStorage.getItem('baimiao_pending_embeddings') || '[]').length;
    } catch {
      return 0;
    }
  })(),

  clearDiaryError: (dateStr) => {
    set((state) => {
      const newMap = { ...state.diaryErrorMap };
      delete newMap[dateStr];
      return { diaryErrorMap: newMap };
    });
  },

  clearMingwuError: () => {
    set({ mingwuError: '' });
  },

  generateDiaryTimeline: async (dateStr, logs, idToOverwrite, targetPromptIndex) => {
    if (!logs || logs.length === 0) return;

    set({ isProcessingDiary: true });
    get().clearDiaryError(dateStr);

    const settings = { ...useSettingsStore.getState() };
    // #5: 使用统一 5 槽名称
    const promptNames = settings.reviewPromptNames || ['日记', '回顾', '自定义 1', '自定义 2', '自定义 3'];

    // Determine active prompt index.
    // 优先使用显式传入的 targetPromptIndex，否则尝试使用待覆盖的原本日记的 Prompt 配置，最后采用全局默认的。
    let activePromptIndex = targetPromptIndex !== undefined
      ? targetPromptIndex
      : 0; // #5: 日记槽位固定为 0

    if (idToOverwrite && targetPromptIndex === undefined) {
      const originalDiary = await db.daily_reviews.get(idToOverwrite);
      if (originalDiary && originalDiary.prompt_index !== undefined) {
        activePromptIndex = originalDiary.prompt_index;
      }
    }

    let activePromptName = promptNames[activePromptIndex] || '日记';
    settings.diaryPromptIndex = activePromptIndex;
    // #5: 从统一 5 槽 reviewPrompts 读取 prompt 内容
    if (settings.reviewPrompts && settings.reviewPrompts[activePromptIndex] !== undefined) {
      settings.diaryPrompt = settings.reviewPrompts[activePromptIndex];
    }
    
    try {
      const response = await fetch('/api/generate-timeline', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          date: dateStr,
          timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
          logs: logs.map(l => ({ id: l.id, content: l.content, created_at: l.created_at })),
          settings
        })
      });
      
      if (!response.ok) {
         const errText = await response.text();
         let errData = { error: errText };
         try { errData = JSON.parse(errText); } catch(e){}
         throw new Error(errData.error || 'AI 服务响应异常，请重试');
      }
      
      const data = await response.json();
      
      // Store the ai_summary inside the timeline_json array for the summary display
      const timelineContent = JSON.stringify([{ summary: data.ai_summary || "暂无内容概要" }]);
      // #31 AI 生成的日记自动打全局标签
      const diaryTags = await processTagsForContent(data.ai_editorial || data.ai_review || '');

      if (idToOverwrite) {
        await db.daily_reviews.update(idToOverwrite, {
           timeline_json: timelineContent,
           ai_summary: data.ai_summary || "暂无内容概要",
           raw_log_ids: logs.map(l => l.id),
           ai_editorial: data.ai_editorial,
           ai_review: data.ai_review,
           prompt_index: activePromptIndex,
           prompt_name: activePromptName,
           tags: diaryTags,
           updated_at: Date.now()
        });
      } else {
        await db.daily_reviews.add({
           id: generateUUID(),
           review_date: dateStr,
           entry_type: 'diary',
           raw_log_ids: logs.map(l => l.id),
           timeline_json: timelineContent,
           ai_editorial: data.ai_editorial,
           ai_summary: data.ai_summary || "暂无内容概要",
           ai_review: data.ai_review || '',
           prompt_index: activePromptIndex,
           prompt_name: activePromptName,
           tags: diaryTags,
           updated_at: Date.now()
        });
      }
    } catch (err: any) {
      console.error("Timeline Generation Error:", err);
      set((state) => ({
        diaryErrorMap: {
          ...state.diaryErrorMap,
          [dateStr]: err.message || "生成时间轴失败，请检查网络连接"
        }
      }));
    } finally {
      set({ isProcessingDiary: false });
    }
  },

  generateReview: async (tempId, dateStr, logs, diaryContent, targetPromptIndex) => {
    if (!logs || logs.length === 0) return;

    set((state) => ({
      isProcessingReviewMap: { ...state.isProcessingReviewMap, [tempId]: true }
    }));
    get().clearDiaryError(dateStr);

    const settings = { ...useSettingsStore.getState() };
    // #5: 使用统一 5 槽名称
    const promptNames = settings.reviewPromptNames || ['日记', '回顾', '自定义 1', '自定义 2', '自定义 3'];

    // Determine active prompt index
    const activePromptIndex = targetPromptIndex !== undefined
      ? targetPromptIndex
      : 1; // #5: 回顾槽位默认为 1

    const activePromptName = promptNames[activePromptIndex] || '回顾';
    settings.reviewPromptIndex = activePromptIndex;
    // #5: 从统一 5 槽 reviewPrompts 读取 prompt 内容
    if (settings.reviewPrompts && settings.reviewPrompts[activePromptIndex] !== undefined) {
      settings.reviewPrompt = settings.reviewPrompts[activePromptIndex];
    }
    
    try {
      const response = await fetch('/api/generate-review', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          date: dateStr,
          timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
          logs: logs.map(l => ({ id: l.id, content: l.content, created_at: l.created_at })),
          diaryContent,
          settings
        })
      });
      
      if (!response.ok) {
         const errText = await response.text();
         let errData = { error: errText };
         try { errData = JSON.parse(errText); } catch(e){}
         throw new Error(errData.error || 'AI 服务响应异常，请重试');
      }
      
      const data = await response.json();
      
      // Always write to the independent daily_reviews table — never touch daily_diaries
      // #31 AI 生成的回顾自动打全局标签
      const reviewTags = await processTagsForContent(data.ai_review || '');
      await db.daily_reviews.add({
        id: generateUUID(),
        review_date: dateStr,
        entry_type: 'review',
        raw_log_ids: logs.map(l => l.id),
        ai_review: data.ai_review || '',
        ai_summary: data.ai_summary || '暂无内容概要',
        prompt_index: activePromptIndex,
        prompt_name: activePromptName,
        tags: reviewTags,
        updated_at: Date.now(),
      });
    } catch (err: any) {
      console.error("Review Generation Error:", err);
      set((state) => ({
        diaryErrorMap: {
          ...state.diaryErrorMap,
          [dateStr]: err.message || "生成回顾失败，请检查网络连接"
        }
      }));
    } finally {
      set((state) => ({
        isProcessingReviewMap: { ...state.isProcessingReviewMap, [tempId]: false }
      }));
    }
  },

  clearAutoGeneratedNotification: () => {
    set({ autoGeneratedNotification: null });
  },

  clearAutoGeneratedReviewNotification: () => {
    set({ autoGeneratedReviewNotification: null });
  },

  addToast: (message, type = 'success') => {
    const id = generateUUID();
    set((state) => ({
      toasts: [...state.toasts, { id, message, type }]
    }));
  },

  removeToast: (id) => {
    set((state) => ({
      toasts: state.toasts.filter((toast) => toast.id !== id)
    }));
  },

  silentlyGenerateDiary: async (dateStr, logs) => {
    if (!logs || logs.length === 0) return;
    if (get().isSilentlyGenerating) return;

    set({ isSilentlyGenerating: true });

    const settings = { ...useSettingsStore.getState() };
    // #5: 日记槽位固定为 slot 0
    const activePromptIndex = 0;
    const promptNames = settings.reviewPromptNames || ['日记', '回顾', '自定义 1', '自定义 2', '自定义 3'];
    const activePromptName = promptNames[0] || '日记';

    try {
      settings.diaryPromptIndex = activePromptIndex;
      if (settings.reviewPrompts && settings.reviewPrompts[activePromptIndex] !== undefined) {
        settings.diaryPrompt = settings.reviewPrompts[activePromptIndex];
      } else {
        settings.diaryPrompt = undefined;
      }

      const response = await fetch('/api/generate-timeline', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          date: dateStr,
          timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
          logs: logs.map(l => ({ id: l.id, content: l.content, created_at: l.created_at })),
          settings
        })
      });

      if (!response.ok) {
        throw new Error(`AI 服务响应异常 (Prompt: ${activePromptName})`);
      }

      const data = await response.json();
      const timelineContent = JSON.stringify([{ summary: data.ai_summary || "暂无内容概要" }]);
      const diaryId = generateUUID();

      await db.daily_reviews.add({
        id: diaryId,
        review_date: dateStr,
        entry_type: 'diary',
        raw_log_ids: logs.map(l => l.id),
        timeline_json: timelineContent,
        ai_editorial: data.ai_editorial,
        ai_summary: data.ai_summary || "暂无内容概要",
        ai_review: data.ai_review || '',
        prompt_index: activePromptIndex,
        prompt_name: activePromptName,
        updated_at: Date.now()
      });

      set({
        autoGeneratedNotification: {
          date: dateStr,
          diaryId: diaryId
        }
      });
    } catch (err: any) {
      console.error("Silent Timeline Generation Error:", err);
    } finally {
      set({ isSilentlyGenerating: false });
    }
  },

  silentlyGenerateReview: async (dateStr, logs) => {
    if (!logs || logs.length === 0) return;
    if (get().isSilentlyGeneratingReview) return;

    set({ isSilentlyGeneratingReview: true });

    const settings = { ...useSettingsStore.getState() };
    // #5: 回顾槽位固定为 slot 1
    const activePromptIndex = 1;
    const promptNames = settings.reviewPromptNames || ['日记', '回顾', '自定义 1', '自定义 2', '自定义 3'];
    const activePromptName = promptNames[1] || '回顾';

    try {
      settings.reviewPromptIndex = activePromptIndex;
      if (settings.reviewPrompts && settings.reviewPrompts[activePromptIndex] !== undefined) {
        settings.reviewPrompt = settings.reviewPrompts[activePromptIndex];
      } else {
        settings.reviewPrompt = undefined;
      }

      const response = await fetch('/api/generate-review', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          date: dateStr,
          timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
          logs: logs.map(l => ({ id: l.id, content: l.content, created_at: l.created_at })),
          diaryContent: '',
          settings
        })
      });

      if (!response.ok) {
        throw new Error(`AI 服务响应异常 (Prompt: ${activePromptName})`);
      }

      const data = await response.json();
      const reviewId = generateUUID();

      await db.daily_reviews.add({
        id: reviewId,
        review_date: dateStr,
        entry_type: 'review',
        raw_log_ids: logs.map(l => l.id),
        ai_review: data.ai_review || '',
        ai_summary: data.ai_summary || '暂无内容概要',
        prompt_index: activePromptIndex,
        prompt_name: activePromptName,
        updated_at: Date.now(),
      });

      set({
        autoGeneratedReviewNotification: {
          date: dateStr,
          reviewId: reviewId
        }
      });
    } catch (err: any) {
      console.error("Silent Review Generation Error:", err);
    } finally {
      set({ isSilentlyGeneratingReview: false });
    }
  },

  generateAllDiaries: async (dateStr, logs) => {
    if (!logs || logs.length === 0) return;
    // #5: 日记槽位固定为 slot 0
    set({ batchProgress: { current: 1, total: 1, type: 'review' } });
    try {
      await get().generateDiaryTimeline(dateStr, logs, undefined, 0);
    } catch (err) {
      console.error(`Batch diary generation failed for slot 0:`, err);
    }
    set({ batchProgress: null });
  },

  generateAllReviews: async (dateStr, logs) => {
    if (!logs || logs.length === 0) return;
    // #5: 回顾槽位固定为 slot 1
    set({ batchProgress: { current: 1, total: 1, type: 'review' } });
    try {
      const tempId = generateUUID();
      await get().generateReview(tempId, dateStr, logs, '', 1);
    } catch (err) {
      console.error(`Batch review generation failed for slot 1:`, err);
    }
    set({ batchProgress: null });
  },

  // #5: 根据选中槽位批量生成（多选浮层「生成 N 篇回顾」按钮调用）
  generateSelected: async (dateStr, logs, selectedIndices) => {
    if (!logs || logs.length === 0) return;
    if (!selectedIndices || selectedIndices.length === 0) return;

    const settings = useSettingsStore.getState();
    const total = selectedIndices.length;

    for (let i = 0; i < selectedIndices.length; i++) {
      const slotIndex = selectedIndices[i];
      set({ batchProgress: { current: i + 1, total, type: 'review' } });
      if (i > 0) {
        await new Promise(r => setTimeout(r, SYNC_CONSTANTS.API_RATE_LIMIT_DELAY_MS));
      }
      try {
        if (isDiarySlot(slotIndex)) {
          // slot 0: 日记 -> /api/generate-timeline, entry_type='diary'
          await get().generateDiaryTimeline(dateStr, logs, undefined, slotIndex);
        } else {
          // slot 1-4: 回顾/自定义 -> /api/generate-review, entry_type='review'
          const tempId = generateUUID();
          await get().generateReview(tempId, dateStr, logs, '', slotIndex);
        }
      } catch (err) {
        console.error(`Batch generation failed for slot ${slotIndex}:`, err);
      }
    }
    set({ batchProgress: null });
  },

  initQueue: () => {
    try {
      const stored = localStorage.getItem('baimiao_autogen_tasks');
      if (stored) {
        let tasks: AutoGenTask[] = JSON.parse(stored);
        const cutoff = Date.now() - 14 * 24 * 60 * 60 * 1000;
        // Clean up outdated tasks that have failed too many times
        tasks = tasks.filter(t => {
          try {
            const taskTime = new Date(t.dateStr).getTime();
            if (taskTime < cutoff && t.status === 'failed') {
              return false;
            }
          } catch {}
          return true;
        });
        // Recover tasks stuck in 'processing' from a previous crashed/closed session
        tasks = tasks.map(t => t.status === 'processing' ? { ...t, status: 'pending' as const } : t);
        set({ autoGenTasks: tasks });
        localStorage.setItem('baimiao_autogen_tasks', JSON.stringify(tasks));
      }
    } catch (e) {
      set({ autoGenTasks: [] });
    }
  },

  checkAndGenerateHistoryTasks: async (daysLimit = 7) => {
    get().initQueue();

    const settings = useSettingsStore.getState();
    // #5: 使用统一 5 槽选中状态替代旧的 diary/review 分别扫描
    const selectedIndices = settings.reviewSelectedIndices || [0, 1];

    if (selectedIndices.length === 0) {
      return;
    }

    const today = new Date();
    const newTasks: AutoGenTask[] = [];

    for (let i = 1; i <= daysLimit; i++) {
      const targetDate = subDays(today, i);
      const dateStr = format(targetDate, 'yyyy-MM-dd');
      const start = startOfDay(targetDate).getTime();
      const end = endOfDay(targetDate).getTime();

      const logs = await db.raw_logs
        .where('created_at')
        .between(start, end)
        .toArray();

      if (logs.length === 0) continue;

      // 获取该日期所有已存在的 daily_reviews
      const existingEntries = await db.daily_reviews
        .where('review_date')
        .equals(dateStr)
        .toArray();

      for (const slotIndex of selectedIndices) {
        const expectedEntryType = getEntryTypeForSlot(slotIndex);
        // 新系统的 prompt_index 就是 slotIndex
        // 旧系统可能存在不同的 prompt_index（通过 getLegacyPromptIndices 映射）
        const legacyIndices = getLegacyPromptIndices(slotIndex);
        const allPossibleIndices = [slotIndex, ...legacyIndices];

        // 检查是否已存在匹配的条目（entry_type + prompt_index）
        const hasExisting = existingEntries.some(
          entry => entry.entry_type === expectedEntryType
            && allPossibleIndices.includes(entry.prompt_index ?? -1)
        );

        if (!hasExisting) {
          newTasks.push({
            id: generateUUID(),
            dateStr,
            type: 'review', // #5: 统一为 'review'，由 promptIndex 决定 API
            promptIndex: slotIndex,
            status: 'pending',
            retryCount: 0
          });
        }
      }
    }

    // De-duplicate and merge with memory queue
    const currentTasks = [...get().autoGenTasks];
    let hasAdded = false;
    for (const nt of newTasks) {
      const exists = currentTasks.some(
        ct => ct.dateStr === nt.dateStr && ct.promptIndex === nt.promptIndex
      );
      if (!exists) {
        currentTasks.push(nt);
        hasAdded = true;
      }
    }

    if (hasAdded) {
      set({ autoGenTasks: currentTasks });
      localStorage.setItem('baimiao_autogen_tasks', JSON.stringify(currentTasks));
    }

    get().processNextQueueTask();
  },

  processNextQueueTask: async () => {
    if (get().isQueuePaused) return;
    if (get().isProcessingQueue) return;
    set({ isProcessingQueue: true });

    const settings = { ...useSettingsStore.getState() };
    const promptNames = settings.reviewPromptNames || ['日记', '回顾', '自定义 1', '自定义 2', '自定义 3'];

    while (true) {
      if (get().isQueuePaused) {
        break;
      }
      const currentTasks = get().autoGenTasks;
      const nextTaskIndex = currentTasks.findIndex(
        t => t.status === 'pending' || (t.status === 'failed' && t.retryCount < 3)
      );

      if (nextTaskIndex === -1) {
        break;
      }

      const task = currentTasks[nextTaskIndex];

      const updatedTasks = [...currentTasks];
      updatedTasks[nextTaskIndex] = { ...task, status: 'processing' };
      set({ autoGenTasks: updatedTasks });
      localStorage.setItem('baimiao_autogen_tasks', JSON.stringify(updatedTasks));

      let success = false;
      try {
        const targetDate = parseISO(task.dateStr);
        const start = startOfDay(targetDate).getTime();
        const end = endOfDay(targetDate).getTime();

        const logs = await db.raw_logs
          .where('created_at')
          .between(start, end)
          .toArray();

        if (logs.length === 0) {
          success = true;
        } else {
          // #5: 由 promptIndex 决定调用哪个 API 和 entry_type
          const activePromptIndex = task.promptIndex;
          const activePromptName = promptNames[activePromptIndex] || '回顾';
          const expectedEntryType = getEntryTypeForSlot(activePromptIndex);

          if (isDiarySlot(activePromptIndex)) {
            // slot 0: 日记 -> /api/generate-timeline
            const reqSettings = { ...settings, diaryPromptIndex: activePromptIndex };
            if (reqSettings.reviewPrompts && reqSettings.reviewPrompts[activePromptIndex] !== undefined) {
              reqSettings.diaryPrompt = reqSettings.reviewPrompts[activePromptIndex];
            } else {
              reqSettings.diaryPrompt = undefined;
            }

            const response = await fetch('/api/generate-timeline', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                date: task.dateStr,
                timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
                logs: logs.map(l => ({ id: l.id, content: l.content, created_at: l.created_at })),
                settings: reqSettings
              })
            });

            if (!response.ok) {
              throw new Error(`AI Service Response Error (Diary prompt index: ${activePromptIndex})`);
            }

            const data = await response.json();
            const timelineContent = JSON.stringify([{ summary: data.ai_summary || "暂无内容概要" }]);

            // 检查是否已有同 prompt_index 的日记条目（含旧索引兼容）
            const legacyIndices = getLegacyPromptIndices(activePromptIndex);
            const allPossibleIndices = [activePromptIndex, ...legacyIndices];
            const existingDiary = await db.daily_reviews
              .where('review_date')
              .equals(task.dateStr)
              .filter(d => d.entry_type === 'diary' && allPossibleIndices.includes(d.prompt_index ?? -1))
              .first();

            if (existingDiary) {
              await db.daily_reviews.update(existingDiary.id, {
                timeline_json: timelineContent,
                raw_log_ids: logs.map(l => l.id),
                ai_editorial: data.ai_editorial,
                ai_summary: data.ai_summary || "暂无内容概要",
                ai_review: data.ai_review,
                prompt_index: activePromptIndex,
                prompt_name: activePromptName,
                updated_at: Date.now()
              });
              set({
                autoGeneratedNotification: {
                  date: task.dateStr,
                  diaryId: existingDiary.id
                }
              });
            } else {
              const newId = generateUUID();
              await db.daily_reviews.add({
                id: newId,
                review_date: task.dateStr,
                entry_type: 'diary',
                raw_log_ids: logs.map(l => l.id),
                timeline_json: timelineContent,
                ai_editorial: data.ai_editorial,
                ai_summary: data.ai_summary || "暂无内容概要",
                ai_review: data.ai_review || '',
                prompt_index: activePromptIndex,
                prompt_name: activePromptName,
                updated_at: Date.now()
              });
              set({
                autoGeneratedNotification: {
                  date: task.dateStr,
                  diaryId: newId
                }
              });
            }
            success = true;
          } else {
            // slot 1-4: 回顾/自定义 -> /api/generate-review
            const reqSettings = { ...settings, reviewPromptIndex: activePromptIndex };
            if (reqSettings.reviewPrompts && reqSettings.reviewPrompts[activePromptIndex] !== undefined) {
              reqSettings.reviewPrompt = reqSettings.reviewPrompts[activePromptIndex];
            } else {
              reqSettings.reviewPrompt = undefined;
            }

            const response = await fetch('/api/generate-review', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                date: task.dateStr,
                timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
                logs: logs.map(l => ({ id: l.id, content: l.content, created_at: l.created_at })),
                diaryContent: '',
                settings: reqSettings
              })
            });

            if (!response.ok) {
              throw new Error(`AI Service Response Error (Review prompt index: ${activePromptIndex})`);
            }

            const data = await response.json();
            const reviewId = generateUUID();

            await db.daily_reviews.add({
              id: reviewId,
              review_date: task.dateStr,
              entry_type: 'review',
              raw_log_ids: logs.map(l => l.id),
              ai_review: data.ai_review || '',
              ai_summary: data.ai_summary || '暂无内容概要',
              prompt_index: activePromptIndex,
              prompt_name: activePromptName,
              updated_at: Date.now(),
            });

            set({
              autoGeneratedReviewNotification: {
                date: task.dateStr,
                reviewId: reviewId
              }
            });
            success = true;
          }
        }
      } catch (err: any) {
        console.error("Queue task execution error:", err);
      }

      const latestTasks = [...get().autoGenTasks];
      const targetIdx = latestTasks.findIndex(t => t.id === task.id);

      if (targetIdx !== -1) {
        if (success) {
          latestTasks.splice(targetIdx, 1);
        } else {
          latestTasks[targetIdx] = {
            ...latestTasks[targetIdx],
            status: 'failed',
            retryCount: latestTasks[targetIdx].retryCount + 1
          };
        }
        set({ autoGenTasks: latestTasks });
        localStorage.setItem('baimiao_autogen_tasks', JSON.stringify(latestTasks));
      }

      const hasMore = get().autoGenTasks.some(
        t => t.status === 'pending' || (t.status === 'failed' && t.retryCount < 3)
      );
      if (hasMore) {
        await new Promise(r => setTimeout(r, SYNC_CONSTANTS.API_RATE_LIMIT_DELAY_MS));
      }
    }

    set({ isProcessingQueue: false });
  },

  clearQueue: () => {
    localStorage.removeItem('baimiao_autogen_tasks');
    set({ autoGenTasks: [], isProcessingQueue: false, isQueuePaused: false });
  },

  setQueuePaused: (paused: boolean) => {
    set({ isQueuePaused: paused });
    if (!paused) {
      get().processNextQueueTask();
    }
  },

  setSearchMode: (open) => {
    set({ isSearchMode: open });
    if (!open) {
      set({ searchQuery: '', searchResults: [], searchError: null, isSearching: false });
    } else {
      get().updateVectorsCount();
    }
  },

  setCopilotMode: (open) => {
    set({ isCopilotMode: open });
  },

  setRandomWalkMode: (open) => {
    set({ isRandomWalkMode: open });
  },

  setThoughtsViewMode: (mode) => {
    set({ thoughtsViewMode: mode });
  },

  setMingwuTimeRange: (range) => {
    set({ mingwuTimeRange: range });
  },

  setMingwuCustomStart: (date) => {
    set({ mingwuCustomStart: date });
  },

  setMingwuCustomEnd: (date) => {
    set({ mingwuCustomEnd: date });
  },

  setSearchQuery: (query) => {
    set({ searchQuery: query });
    // Debounce so we don't fire an embedding request + full-table scans per keystroke
    if (searchDebounceTimer) clearTimeout(searchDebounceTimer);
    searchDebounceTimer = setTimeout(() => {
      get().executeSearch();
    }, 250);
  },

  setSearchFilters: (filters) => {
    set({ searchFilters: filters });
    get().executeSearch();
  },

  clearSearchHistory: () => {
    localStorage.removeItem('baimiao_search_history');
    set({ searchHistory: [] });
  },

  executeSearch: async () => {
    const { searchQuery, searchFilters } = get();
    if (!searchQuery.trim()) {
      set({ searchResults: [], searchError: null, isSearching: false });
      return;
    }

    const myRequestId = ++searchRequestId;
    set({ isSearching: true, searchError: null });

    const query = searchQuery.trim();
    const { dateRange, modules, customStartDate, customEndDate, diaryPromptIndex } = searchFilters;
    const filterRange = getFilterRange(dateRange, customStartDate, customEndDate);
    const results: SearchItem[] = [];
    const seenIds = new Set<string>();
    // #32 标签前缀搜索：query 以 # 开头时按标签路径前缀匹配（搜 #工作 返回 工作/项目A 等子标签内容）
    const queryTag = query.startsWith('#') ? normalizeTagPath(query.slice(1)) : '';

    // --- Semantic search branch ---
    const settings = useSettingsStore.getState();
    const { semanticSearchEnabled } = get();
    const useSemanticSearch = semanticSearchEnabled && settings.embedEnabled && (settings.embedProvider === 'custom' || settings.embedApiKey || settings.apiKey);
    let queryEmbedding: number[] | null = null;

    if (useSemanticSearch) {
      try {
        queryEmbedding = await requestEmbedding(query);
      } catch (err: any) {
        console.error('[Semantic Search] Failed to get query embedding:', err);
        set({ searchError: err.message || '生成搜索向量失败，请检查设置或网络' });
      }
      // A newer search may have started while awaiting the embedding; abort early
      if (myRequestId !== searchRequestId) return;
    }

    // 1. 碎屑记录搜索
    if (modules.includes('record')) {
      const logs = await db.raw_logs.toArray();
      const matchedLogs = logs.filter(log => {
        const matchesQuery = log.content.toLowerCase().includes(query.toLowerCase())
          || (!!queryTag && !!(log.tags && log.tags.some(t => matchesByPrefix(t, queryTag))));
        const matchesDate = isDateInFilter(log.created_at, dateRange, customStartDate, customEndDate);
        return matchesQuery && matchesDate;
      });

      results.push(...matchedLogs.map(log => ({
        id: log.id,
        type: 'record' as const,
        title: `碎屑记录 · ${format(new Date(log.created_at), 'yyyy-MM-dd HH:mm')}`,
        content: log.content,
        date: format(new Date(log.created_at), 'yyyy-MM-dd'),
        highlightSnippets: getHighlightSnippet(log.content, query)
      })));
    }

    // 2. 日记搜索
    const showDiary = modules.includes('diary');
    const showReview = modules.includes('review');
    if (showDiary) {
      const diaries = await db.daily_reviews.filter(d => d.entry_type === 'diary').toArray();
      const matchedDiaries = diaries.filter(d => {
        const diaryDateObj = parseISO(d.review_date);
        return isDateInFilter(diaryDateObj, dateRange, customStartDate, customEndDate);
      });

      matchedDiaries.forEach(d => {
        if ((d.ai_editorial && d.ai_editorial.toLowerCase().includes(query.toLowerCase()))
          || (!!queryTag && !!(d.tags && d.tags.some(t => matchesByPrefix(t, queryTag))))) {
          results.push({
            id: d.id,
            type: 'diary' as const,
            title: `整合日记 · ${d.review_date}`,
            content: d.ai_editorial,
            date: d.review_date,
            highlightSnippets: getHighlightSnippet(d.ai_editorial, query)
          });
        }
      });
    }

    // 3. 回顾搜索（daily_reviews 表中 entry_type='review'）
    if (showReview) {
      const reviews = await db.daily_reviews.filter(r => r.entry_type === 'review').toArray();
      const matchedReviews = reviews.filter(r => {
        const reviewDateObj = parseISO(r.review_date);
        const matchesText = !!(r.ai_review && r.ai_review.toLowerCase().includes(query.toLowerCase()));
        const matchesTag = !!queryTag && !!(r.tags && r.tags.some(t => matchesByPrefix(t, queryTag)));
        return isDateInFilter(reviewDateObj, dateRange, customStartDate, customEndDate) && (matchesText || matchesTag);
      });

      matchedReviews.forEach(r => {
        results.push({
          id: r.id,
          type: 'review' as const,
          title: `反思回顾 · ${r.review_date}`,
          content: r.ai_review,
          date: r.review_date,
          highlightSnippets: getHighlightSnippet(r.ai_review, query)
        });
      });
    }

    // 4. 洞察搜索（mingwu 表）
    if (modules.includes('insight')) {
      const insights = await db.mingwu.toArray();
      const matchedInsights = insights.filter(ins => {
        const matchesQuery = ins.content.toLowerCase().includes(query.toLowerCase())
          || (!!queryTag && !!(ins.tags && ins.tags.some(t => matchesByPrefix(t, queryTag))));
        const matchesDate = isDateInFilter(ins.created_at, dateRange, customStartDate, customEndDate);
        return matchesQuery && matchesDate;
      });

      results.push(...matchedInsights.map(ins => ({
        id: ins.id || generateUUID(),
        type: 'insight' as const,
        title: `生命洞察 · ${ins.range_label}`,
        content: ins.content,
        date: ins.start_date,
        highlightSnippets: getHighlightSnippet(ins.content, query)
      })));
    }

    // 按日期倒序排列
    results.sort((a, b) => b.date.localeCompare(a.date));
    // Track IDs from text search to avoid duplicates in semantic results
    results.forEach(r => seenIds.add(r.id));

    // --- Semantic search: merge vector matches ---
    if (queryEmbedding && queryEmbedding.length > 0) {
      const semanticResults: Array<SearchItem & { similarity: number }> = [];

      // Gather survivors of date/prompt/seenIds/embedding pre-filtering into a
      // candidate list for the worker. Metadata is stored alongside so the
      // worker-returned scores can be mapped back to SearchItems without the
      // worker needing to know about Dexie records (PRD §4.3.4).
      const candidates: CosineCandidate[] = [];
      const metaByKey = new Map<string, SearchItem>();

      if (modules.includes('record')) {
        // Pre-filter by the created_at index when a bounded range is set, instead of
        // loading the whole table (PRD §4.3.4). Fall back to toArray() for "全部".
        const logs = filterRange
          ? await db.raw_logs.where('created_at').between(filterRange.start, filterRange.end).toArray()
          : await db.raw_logs.toArray();
        for (const log of logs.slice(0, MAX_SEMANTIC_CANDIDATES)) {
          if (!log.embedding || log.embedding.length === 0) continue;
          if (seenIds.has(log.id)) continue;
          const key = `record:${log.id}`;
          metaByKey.set(key, {
            id: log.id,
            type: 'record',
            title: `[语义] 碎屑记录 . ${format(new Date(log.created_at), 'yyyy-MM-dd HH:mm')}`,
            content: log.content,
            date: format(new Date(log.created_at), 'yyyy-MM-dd'),
            highlightSnippets: getHighlightSnippet(log.content, query),
          });
          candidates.push({ key, embedding: log.embedding });
        }
      }

      if (modules.includes('diary')) {
        const diaries = (await db.daily_reviews.filter(d => d.entry_type === 'diary').toArray()).slice(0, MAX_SEMANTIC_CANDIDATES);
        for (const d of diaries) {
          if (!d.embedding || d.embedding.length === 0) continue;
          if (seenIds.has(d.id)) continue;
          if (!isDateInFilter(parseISO(d.review_date), dateRange, customStartDate, customEndDate)) continue;
          // Multi-template isolation (PRD §4.3.2): when a diary prompt is selected,
          // restrict semantic matches to that template only.
          if (diaryPromptIndex !== undefined && d.prompt_index !== diaryPromptIndex) continue;
          const key = `diary:${d.id}`;
          metaByKey.set(key, {
            id: d.id,
            type: 'diary',
            title: `[语义] 整合日记 . ${d.review_date}`,
            content: d.ai_editorial,
            date: d.review_date,
            highlightSnippets: getHighlightSnippet(d.ai_editorial || '', query),
          });
          candidates.push({ key, embedding: d.embedding });
        }
      }

      if (modules.includes('review')) {
        const reviews = (await db.daily_reviews.filter(r => r.entry_type === 'review').toArray()).slice(0, MAX_SEMANTIC_CANDIDATES);
        for (const r of reviews) {
          if (!r.embedding || r.embedding.length === 0) continue;
          if (seenIds.has(r.id)) continue;
          if (!isDateInFilter(parseISO(r.review_date), dateRange, customStartDate, customEndDate)) continue;
          const key = `review:${r.id}`;
          metaByKey.set(key, {
            id: r.id,
            type: 'review',
            title: `[语义] 反思回顾 . ${r.review_date}`,
            content: r.ai_review,
            date: r.review_date,
            highlightSnippets: getHighlightSnippet(r.ai_review || '', query),
          });
          candidates.push({ key, embedding: r.embedding });
        }
      }

      if (modules.includes('insight')) {
        const insights = (await db.mingwu.toArray()).slice(0, MAX_SEMANTIC_CANDIDATES);
        for (const ins of insights) {
          if (!ins.embedding || ins.embedding.length === 0) continue;
          if (!ins.id) continue;
          if (seenIds.has(ins.id)) continue;
          if (!isDateInFilter(ins.created_at, dateRange, customStartDate, customEndDate)) continue;
          const key = `insight:${ins.id}`;
          metaByKey.set(key, {
            id: ins.id,
            type: 'insight',
            title: `[语义] 生命洞察 . ${ins.range_label}`,
            content: ins.content,
            date: ins.start_date,
            highlightSnippets: getHighlightSnippet(ins.content || '', query),
          });
          candidates.push({ key, embedding: ins.embedding });
        }
      }

      // Cosine scoring runs in a Web Worker to keep the main thread responsive
      // (PRD §2 / §4.3.4). Falls back to an inline main-thread loop if the
      // worker is unavailable, so semantic search still works on old WebViews.
      let scores: CosineScore[];
      try {
        const res = await computeCosineBatch(queryEmbedding, candidates, SEMANTIC_THRESHOLD);
        // A newer search may have started while the worker was computing; drop this result.
        if (myRequestId !== searchRequestId) return;
        scores = res.results;
      } catch (err) {
        console.warn('[Semantic Search] worker unavailable, falling back to main thread:', err);
        scores = [];
        for (const c of candidates) {
          const sim = cosineSimilarity(queryEmbedding, c.embedding);
          if (sim > SEMANTIC_THRESHOLD) scores.push({ key: c.key, sim });
        }
        scores.sort((a, b) => b.sim - a.sim);
      }

      for (const { key, sim } of scores) {
        const item = metaByKey.get(key);
        if (item) semanticResults.push({ ...item, similarity: sim });
      }

      // Sort semantic results by similarity descending, take top 20
      semanticResults.sort((a, b) => b.similarity - a.similarity);
      const topSemantic = semanticResults.slice(0, 20).map(({ similarity, ...rest }) => rest);

      // Reciprocal Rank Fusion: merge keyword (date-ranked) and semantic (similarity-ranked)
      // lists into one ranked list, instead of blindly prepending semantic results which
      // could bury an exact keyword match behind tangential semantic hits.
      const RRF_K = 60;
      const rrf = new Map<string, number>();
      results.forEach((r, i) => rrf.set(r.id, 1 / (RRF_K + i + 1)));
      topSemantic.forEach((r, i) => rrf.set(r.id, (rrf.get(r.id) || 0) + 1 / (RRF_K + i + 1)));
      const merged = [...results, ...topSemantic];
      merged.sort((a, b) => (rrf.get(b.id) || 0) - (rrf.get(a.id) || 0));
      results.length = 0;
      results.push(...merged);
    }

    // Discard this result if a newer search has superseded it
    if (myRequestId !== searchRequestId) return;
    set({ searchResults: results, isSearching: false });
  },

  addSearchHistory: (query) => {
    if (!query || !query.trim()) return;
    const trimmed = query.trim();
    set(state => {
      const newHistory = [trimmed, ...state.searchHistory.filter(h => h !== trimmed)].slice(0, 10);
      localStorage.setItem('baimiao_search_history', JSON.stringify(newHistory));
      return { searchHistory: newHistory };
    });
  },

  setSemanticSearchEnabled: (enabled) => {
    set({ semanticSearchEnabled: enabled });
    // Re-execute search if query exists
    const { searchQuery } = get();
    if (searchQuery.trim()) {
      get().executeSearch();
    }
  },

  updateVectorsCount: async () => {
    try {
      const logCount = await db.raw_logs.filter(log => !!log.embedding && log.embedding.length > 0).count();
      const diaryCount = await db.daily_reviews.filter(d => d.entry_type === 'diary' && !!d.embedding && d.embedding.length > 0).count();
      const reviewCount = await db.daily_reviews.filter(r => r.entry_type === 'review' && !!r.embedding && r.embedding.length > 0).count();
      const insightCount = await db.mingwu.filter(ins => !!ins.embedding && ins.embedding.length > 0).count();
      set({ totalVectorsCount: logCount + diaryCount + reviewCount + insightCount });
    } catch (e) {
      console.error('Failed to update vectors count:', e);
    }
  },

  setSyncStatus: (status, errorMsg) => set({ syncStatus: status, syncErrorMessage: errorMsg || '' }),

  syncNow: async (forcePolicy) => {
    const settings = useSettingsStore.getState();
    if (!settings.syncEnabled) {
      set({ syncStatus: 'disabled', syncErrorMessage: '' });
      return;
    }

    // 1. 根据不同服务商做针对性的配置校验
    if (settings.syncProvider === 'webdav') {
      if (!settings.syncPassword || !settings.syncPasswordE2EE) {
        set({ syncStatus: 'credentials_missing', syncErrorMessage: '同步密码未保存，请补充密码以恢复自动同步。' });
        return;
      }
      if (!settings.syncEndpoint || !settings.syncUsername) {
        set({ syncStatus: 'error', syncErrorMessage: 'WebDAV 云同步配置不完整，请检查设置。' });
        return;
      }
    } else if (settings.syncProvider === 'onedrive') {
      if (!settings.syncPasswordE2EE) {
        set({ syncStatus: 'credentials_missing', syncErrorMessage: '加密密码未保存，请补充密码以恢复自动同步。' });
        return;
      }
      if (!settings.syncOneDriveToken) {
        set({ syncStatus: 'error', syncErrorMessage: 'OneDrive 尚未授权，请先授权。' });
        return;
      }
    } else if (settings.syncProvider === 'gdrive') {
      if (!settings.syncPasswordE2EE) {
        set({ syncStatus: 'credentials_missing', syncErrorMessage: '加密密码未保存，请补充密码以恢复自动同步。' });
        return;
      }
      if (!settings.syncGDriveToken) {
        set({ syncStatus: 'error', syncErrorMessage: 'Google Drive 尚未授权，请先授权。' });
        return;
      }
    } else if (settings.syncProvider === 'dropbox') {
      if (!settings.syncPasswordE2EE) {
        set({ syncStatus: 'credentials_missing', syncErrorMessage: '加密密码未保存，请补充密码以恢复自动同步。' });
        return;
      }
      if (!settings.syncDropboxToken) {
        set({ syncStatus: 'error', syncErrorMessage: 'Dropbox 尚未授权，请先授权。' });
        return;
      }
    } else {
      set({ syncStatus: 'error', syncErrorMessage: '未知的云同步服务商。' });
      return;
    }

    set({ syncStatus: 'syncing', syncErrorMessage: '' });

    try {
      let client: any;
      if (settings.syncProvider === 'webdav') {
        client = new WebDAVClient(settings.syncEndpoint, settings.syncUsername, settings.syncPassword);
      } else if (settings.syncProvider === 'onedrive') {
        client = new OneDriveClient(settings.syncOneDriveToken || '');
      } else if (settings.syncProvider === 'gdrive') {
        client = new GDriveClient(settings.syncGDriveToken || '');
      } else if (settings.syncProvider === 'dropbox') {
        client = new DropboxClient(settings.syncDropboxToken || '');
      }
      
      // 1. 确保云端目录存在
      const dirExists = await client.checkDir(settings.syncDirectory);
      if (!dirExists) {
        await client.createDir(settings.syncDirectory);
      }

      // 2. 尝试从云端拉取已有的加密备份
      const syncFilePath = `${settings.syncDirectory}data.enc`;
      let cloudData: any = null;
      try {
        const encryptedBuffer = await client.getFile(syncFilePath);
        const decryptedText = await decryptData(encryptedBuffer, settings.syncPasswordE2EE);
        cloudData = JSON.parse(decryptedText);
      } catch (err: any) {
        if (err.message !== 'FILE_NOT_FOUND') {
          throw err; 
        }
      }

      // 3. 收集本地数据
      const localLogs = await db.raw_logs.toArray();
      const localDiaries = await db.daily_reviews.filter(d => d.entry_type === 'diary').toArray();
      const localReviews = await db.daily_reviews.filter(r => r.entry_type === 'review').toArray();
      const localInsights = await db.mingwu.toArray();

      // 4. 数据合并
      const policy = forcePolicy || settings.syncConflictPolicy || 'merge';

      if (cloudData && cloudData.version === 1 && policy !== 'local_wins') {
        if (policy === 'cloud_wins') {
          // 清空本地数据，以云端为绝对基准
          await db.raw_logs.clear();
          await db.daily_reviews.clear();
          await db.mingwu.clear();
        }

        // 合并 logs
        if (cloudData.logs && Array.isArray(cloudData.logs)) {
          for (const cLog of cloudData.logs) {
            const exist = await db.raw_logs.get(cLog.id);
            if (!exist) {
              if (cLog.audioDataUrl) {
                try {
                  const res = await fetch(cLog.audioDataUrl);
                  cLog.audioBlob = await res.blob();
                } catch(e) {
                  console.error("Failed to restore audioBlob, keeping text", e);
                }
                delete cLog.audioDataUrl;
              }
              await db.raw_logs.add(cLog);
            }
          }
        }
        // 合并 diaries（兼容旧 daily_diaries 格式 -> daily_reviews entry_type='diary'）
        if (cloudData.diaries && Array.isArray(cloudData.diaries)) {
          for (const cDiary of cloudData.diaries) {
            const mapped: any = normalizeLegacyDiary(cDiary);
            const exist = await db.daily_reviews.get(mapped.id);
            if (!exist) {
              await db.daily_reviews.add(mapped);
            } else if (policy === 'cloud_wins' || mapped.updated_at > exist.updated_at) {
              await db.daily_reviews.put(mapped);
            }
          }
        }
        // 合并 reviews（兼容旧 review_prompt_* -> prompt_*，补 entry_type='review'）
        if (cloudData.reviews && Array.isArray(cloudData.reviews)) {
          for (const cReview of cloudData.reviews) {
            const mapped: any = normalizeLegacyReview(cReview);
            const exist = await db.daily_reviews.get(mapped.id);
            if (!exist) {
              await db.daily_reviews.add(mapped);
            } else if (policy === 'cloud_wins' || mapped.updated_at > exist.updated_at) {
              await db.daily_reviews.put(mapped);
            }
          }
        }
        // 合并 insights（-> mingwu，补 mingwu_type）
        if (cloudData.insights && Array.isArray(cloudData.insights)) {
          for (const cInsight of cloudData.insights) {
            const mapped: any = normalizeLegacyInsight(cInsight);
            const exist = await db.mingwu.get(mapped.id);
            if (!exist) {
              await db.mingwu.add(mapped);
            } else if (policy === 'cloud_wins' || mapped.created_at > exist.created_at) {
              await db.mingwu.put(mapped);
            }
          }
        }
      }

      // 5. 重新读取合并后的最新本地数据，并加密上传到云端
      const mergedLogs = await db.raw_logs.toArray();
      const mergedDiaries = await db.daily_reviews.filter(d => d.entry_type === 'diary').toArray();
      const mergedReviews = await db.daily_reviews.filter(r => r.entry_type === 'review').toArray();
      const mergedInsights = await db.mingwu.toArray();

      const packedMergedLogs = await Promise.all(mergedLogs.map(async l => {
        if (l.audioBlob) {
          const dataUrl = await new Promise<string>((resolve, reject) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve(reader.result as string);
            reader.onerror = reject;
            reader.readAsDataURL(l.audioBlob!);
          });
          return { ...l, audioBlob: undefined, audioDataUrl: dataUrl };
        }
        return l;
      }));

      const exportPayload = {
        "version": 1,
        exported_at: Date.now(),
        logs: packedMergedLogs,
        diaries: mergedDiaries,
        reviews: mergedReviews,
        insights: mergedInsights
      };

      const payloadJson = JSON.stringify(exportPayload);
      const encryptedBuffer = await encryptData(payloadJson, settings.syncPasswordE2EE);
      
      await client.putFile(syncFilePath, encryptedBuffer);

      // 6. 更新成功状态
      settings.setSettings({ syncLastTime: Date.now() });
      set({ syncStatus: 'idle', syncErrorMessage: '' });
    } catch (err: any) {
      console.error("Sync process failed:", err);
      set({ 
        syncStatus: 'error', 
        syncErrorMessage: err.message || "连接网盘或加密失败" 
      });
    }
  }
}));

registerQueueChangeListener((size) => {
  useAppStore.setState({ embeddingQueueSize: size });
});

// Minimum cosine similarity for a vector match to be included in semantic
// search results. Tunable single source of truth. Exported so the Copilot
// RAG retrieval shares the same threshold.
export const SEMANTIC_THRESHOLD = 0.35;

// Hard cap on how many candidates the main-thread cosine loop compares per
// entity type, per PRD §4.3.4 (protects mobile CPU). Candidates are sliced
// after date/prompt pre-filtering, before similarity scoring.
export const MAX_SEMANTIC_CANDIDATES = 1000;

// === 搜索辅助函数 ===
export const isDateInFilter = (
  date: Date | number, 
  range: string, 
  customStartDate?: string, 
  customEndDate?: string
): boolean => {
  if (range === '全部') return true;
  const now = new Date();
  const target = typeof date === 'number' ? new Date(date) : date;
  
  let start: Date;
  let end: Date;

  if (range === '本周') {
    start = startOfWeek(now, { weekStartsOn: 1 });
    end = endOfWeek(now, { weekStartsOn: 1 });
  } else if (range === '本月') {
    start = startOfMonth(now);
    end = endOfMonth(now);
  } else if (range === '本季度') {
    start = startOfQuarter(now);
    end = endOfQuarter(now);
  } else if (range === '自定义') {
    if (!customStartDate && !customEndDate) return true;
    
    const startObj = customStartDate ? startOfDay(parseISO(customStartDate)) : new Date(0);
    const endObj = customEndDate ? endOfDay(parseISO(customEndDate)) : new Date(8640000000000000);

    return isWithinInterval(target, { start: startObj, end: endObj });
  } else {
    return true;
  }

  return isWithinInterval(target, { start, end });
};

// Returns the [start, end] timestamp window for a date filter, or null when
// the range is unbounded ("全部"). Used to drive IndexedDB index pre-filtering
// (where('created_at').between(...)) before the cosine loop, so we don't load
// the full table into memory on every search (PRD §4.3.4). Exported for the
// Copilot RAG retrieval to share the same pre-filtering logic.
export const getFilterRange = (
  range: string,
  customStartDate?: string,
  customEndDate?: string
): { start: number; end: number } | null => {
  if (range === '全部') return null;
  const now = new Date();
  let start: Date;
  let end: Date;
  if (range === '本周') {
    start = startOfWeek(now, { weekStartsOn: 1 });
    end = endOfWeek(now, { weekStartsOn: 1 });
  } else if (range === '本月') {
    start = startOfMonth(now);
    end = endOfMonth(now);
  } else if (range === '本季度') {
    start = startOfQuarter(now);
    end = endOfQuarter(now);
  } else if (range === '自定义') {
    if (!customStartDate && !customEndDate) return null;
    start = customStartDate ? startOfDay(parseISO(customStartDate)) : new Date(0);
    end = customEndDate ? endOfDay(parseISO(customEndDate)) : new Date(8640000000000000);
  } else {
    return null;
  }
  return { start: start.getTime(), end: end.getTime() };
};

const escapeHtml = (str: string) => str
  .replace(/&/g, '&amp;')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;')
  .replace(/'/g, '&#39;');

const escapeRegExp = (str: string) => {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
};

// Debounce timer + monotonic request id for search. The id lets a newer search
// discard the result of a slower in-flight one (e.g. a semantic embedding call
// that completes after the user kept typing).
let searchDebounceTimer: ReturnType<typeof setTimeout> | null = null;
let searchRequestId = 0;

const getHighlightSnippet = (text: string, query: string): string => {
  if (!text) return '';
  const cleanText = text.replace(/[\r\n]+/g, ' '); // 扁平化多行文本
  const index = cleanText.toLowerCase().indexOf(query.toLowerCase());

  if (index === -1) {
    return escapeHtml(cleanText.slice(0, 80)) + (cleanText.length > 80 ? '...' : '');
  }

  const start = Math.max(0, index - 20);
  const end = Math.min(cleanText.length, index + query.length + 40);
  let snippet = cleanText.slice(start, end);

  if (start > 0) snippet = '...' + snippet;
  if (end < cleanText.length) snippet = snippet + '...';

  // Escape HTML first (prevents XSS from imported/synced content rendered via
  // dangerouslySetInnerHTML), then highlight the query match. The query is escaped
  // the same way so its HTML-special chars match the escaped snippet.
  const escaped = escapeHtml(snippet);
  const escapedQuery = escapeRegExp(escapeHtml(query));
  const regex = new RegExp(`(${escapedQuery})`, 'gi');
  return escaped.replace(regex, '<mark class="bg-amber-100 text-amber-900 rounded-[3px] px-0.5 font-medium">$1</mark>');
};
