import React, { useState, useEffect, useRef } from 'react';
import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { Loader2, SlidersHorizontal, X, Search, Trash2, ChevronDown, Cloud, CloudOff, CloudLightning, Sparkles, MessageSquare, Calendar as CalendarIcon } from 'lucide-react';
import { ChatCircleDots, Notepad, HeadCircuit, Clock } from '@phosphor-icons/react';
import { subDays, startOfDay, endOfDay, format } from 'date-fns';
import { db } from '../db/db';
import { useAppStore } from '../store/app.store';
import { useSettingsStore } from '../store/settings.store';
import MiniCalendar from './MiniCalendar';
import Copilot from '../pages/Copilot';

export default function Layout() {
  const navigate = useNavigate();
  const [showAboutModal, setShowAboutModal] = useState(false);
  const [isUpdating, setIsUpdating] = useState(false);

  const { 
    autoGeneratedNotification, 
    clearAutoGeneratedNotification, 
    autoGeneratedReviewNotification,
    clearAutoGeneratedReviewNotification,
    autoGenTasks,
    isProcessingQueue,
    isQueuePaused,
    checkAndGenerateHistoryTasks,
    isSearchMode,
    searchQuery,
    searchHistory,
    searchFilters,
    searchResults,
    setSearchMode,
    setSearchQuery,
    setSearchFilters,
    clearSearchHistory,
    addSearchHistory,
    syncStatus,
    syncErrorMessage,
    syncNow,
    semanticSearchEnabled,
    setSemanticSearchEnabled,
    isSearching,
    searchError,
    totalVectorsCount,
    embeddingQueueSize,
    isCopilotMode,
    setCopilotMode
  } = useAppStore();

  const { syncEnabled, embedEnabled, diaryPrompts } = useSettingsStore();

  const [showDateDropdown, setShowDateDropdown] = useState(false);
  const dateDropdownRef = useRef<HTMLDivElement>(null);
  const dropdownCardRef = useRef<HTMLDivElement>(null);
  const [showPromptDropdown, setShowPromptDropdown] = useState(false);
  const promptDropdownRef = useRef<HTMLDivElement>(null);
  const promptCardRef = useRef<HTMLDivElement>(null);
  const [promptCardPos, setPromptCardPos] = useState<{ top: number; left: number } | null>(null);

  const [tempStartDate, setTempStartDate] = useState(searchFilters.customStartDate || '');
  const [tempEndDate, setTempEndDate] = useState(searchFilters.customEndDate || '');
  const [calendarTarget, setCalendarTarget] = useState<'none' | 'start' | 'end'>('none');

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      const clickedBtn = dateDropdownRef.current && dateDropdownRef.current.contains(event.target as Node);
      const clickedCard = dropdownCardRef.current && dropdownCardRef.current.contains(event.target as Node);
      if (!clickedBtn && !clickedCard) {
        setShowDateDropdown(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, []);

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      const inButton = promptDropdownRef.current && promptDropdownRef.current.contains(event.target as Node);
      const inCard = promptCardRef.current && promptCardRef.current.contains(event.target as Node);
      if (!inButton && !inCard) {
        setShowPromptDropdown(false);
        setPromptCardPos(null);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, []);

  useEffect(() => {
    if (showDateDropdown) {
      setTempStartDate(searchFilters.customStartDate || '');
      setTempEndDate(searchFilters.customEndDate || '');
    }
    setCalendarTarget('none');
  }, [showDateDropdown, searchFilters.customStartDate, searchFilters.customEndDate]);

  const formatCustomDateLabel = (start: string, end: string) => {
    try {
      const s = start.slice(5); // "MM-DD"
      const e = end.slice(5); // "MM-DD"
      return `${s} ~ ${e}`;
    } catch (err) {
      return '自定义';
    }
  };

  const handleResultClick = (item: any) => {
    if (searchQuery.trim()) {
      addSearchHistory(searchQuery);
    }
    setSearchMode(false);
    if (item.type === 'record') {
      navigate(`/?date=${item.date}`);
    } else if (item.type === 'diary') {
      navigate(`/diary?date=${item.date}`);
    } else if (item.type === 'review') {
      navigate(`/review?date=${item.date}`);
    } else if (item.type === 'insight') {
      // 洞察页不需要日期，直接导航到洞察大板块
      navigate('/insights');
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' && searchQuery.trim()) {
      addSearchHistory(searchQuery);
      (e.target as HTMLInputElement).blur(); // 收起键盘
    }
  };

  useEffect(() => {
    checkAndGenerateHistoryTasks(7);
  }, []);

  const handleForceUpdate = async () => {
    setIsUpdating(true);
    await new Promise(resolve => setTimeout(resolve, 100)); // 留 100ms 缓冲让 loading 样式顺畅渲染
    try {
      if ('serviceWorker' in navigator) {
        const registrations = await navigator.serviceWorker.getRegistrations();
        for (let registration of registrations) {
          await registration.update(); // 强制 Service Worker 检查并拉取最新资源
        }
      }
      // 强制 500ms 垫底延时以防动画瞬间闪过，建立良好的升级心智预期
      await new Promise(resolve => setTimeout(resolve, 500));
      window.location.reload();
    } catch (err) {
      await new Promise(resolve => setTimeout(resolve, 500));
      window.location.reload();
    }
  };

  const togglePromptDropdown = () => {
    // Measure the button position so the dropdown card (rendered outside the
    // overflow-x-auto filter row to avoid clipping) can anchor to it.
    if (!showPromptDropdown && promptDropdownRef.current) {
      const r = promptDropdownRef.current.getBoundingClientRect();
      setPromptCardPos({ top: r.bottom + 4, left: r.left });
    }
    setShowPromptDropdown(!showPromptDropdown);
    setShowDateDropdown(false);
  };

  return (
    <div className="flex flex-col h-full bg-[#f0eef5] font-sans text-stone-900 overflow-hidden items-center justify-center">
      <div className="w-full max-w-md h-full bg-white shadow-sm ring-1 ring-black/5 flex flex-col relative overflow-hidden">
        {/* Global Nav */}
        {!isCopilotMode && (
          <header className="flex h-[54px] shrink-0 items-center justify-between px-4 bg-gradient-to-r from-baimiao-mysteria to-[#2c2957] text-white/95 border-b border-white/5">
            <div className="flex items-center gap-2">
              <h1 
                onClick={() => setShowAboutModal(true)} 
                className="text-[18px] font-normal font-serif tracking-widest cursor-pointer hover:opacity-80 transition-opacity active:scale-[0.98] select-none translate-y-[2px]"
              >
                白描笔记
              </h1>
              {autoGenTasks.length > 0 && (isProcessingQueue || isQueuePaused) && (
                <span className={`flex items-center gap-1 bg-white/10 text-white/90 border border-white/10 text-[10px] px-2 py-0.5 rounded-full font-medium select-none tracking-wide ${isQueuePaused ? 'opacity-65' : 'animate-pulse'}`}>
                  <Loader2 className={`w-2.5 h-2.5 text-white/60 ${isQueuePaused ? '' : 'animate-spin'}`} />
                  {isQueuePaused ? `整理已暂停 (${autoGenTasks.length})` : `AI 整理中 (${autoGenTasks.length})`}
                </span>
              )}
            </div>
            <div className="flex items-center gap-3">
              {syncEnabled && (
                <button 
                  onClick={() => syncNow()}
                  disabled={syncStatus === 'syncing'}
                  title={syncStatus === 'error' ? `同步出错: ${syncErrorMessage}` : '点击手动同步'}
                  className="p-1.5 hover:opacity-70 transition-opacity active:scale-95 disabled:opacity-80 shrink-0"
                >
                  {syncStatus === 'syncing' && <Loader2 className="w-[18px] h-[18px] text-blue-400 animate-spin" />}
                  {syncStatus === 'idle' && <Cloud className="w-[18px] h-[18px] text-emerald-400 fill-emerald-500/10" />}
                  {syncStatus === 'error' && <CloudLightning className="w-[18px] h-[18px] text-red-400 animate-bounce" />}
                  {syncStatus === 'disabled' && <CloudOff className="w-[18px] h-[18px] text-stone-500" />}
                </button>
              )}
              <button
                onClick={() => setSearchMode(true)}
                className="p-1.5 hover:opacity-70 transition-opacity active:scale-95"
              >
                <Search className="w-[18px] h-[18px]" />
              </button>
              <button
                onClick={() => setCopilotMode(true)}
                title="白描 Copilot"
                className="p-1.5 hover:opacity-70 transition-opacity active:scale-95"
              >
                <MessageSquare className="w-[18px] h-[18px]" />
              </button>
              <button
                onClick={() => navigate('/settings')}
                className="p-1.5 hover:opacity-70 transition-opacity -mr-1.5 active:scale-95"
              >
                <SlidersHorizontal className="w-[18px] h-[18px]" />
              </button>
            </div>
          </header>
        )}

        {/* Global Auto-Generated Notification Toast */}
        {autoGeneratedNotification && (
          <div className="bg-stone-900 text-stone-100 text-[13px] px-4 py-2.5 flex items-center justify-between shrink-0 animate-in slide-in-from-top duration-300 z-40 border-b border-stone-850">
            <span className="flex items-center gap-1.5 font-medium select-none text-[12.5px]">
              <span className="animate-pulse">🪄</span> 
              已自动为您整理 {autoGeneratedNotification.date} 的日记
            </span>
            <div className="flex items-center gap-2">
              <button 
                onClick={() => {
                  navigate(`/diary?date=${autoGeneratedNotification.date}`);
                  clearAutoGeneratedNotification();
                }}
                className="bg-white text-black px-2.5 py-1 rounded-md text-[11px] font-semibold hover:bg-stone-200 transition-colors"
              >
                查看
              </button>
              <button 
                onClick={clearAutoGeneratedNotification}
                className="p-1 text-stone-400 hover:text-stone-200 transition-colors"
              >
                <X className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        )}

        {autoGeneratedReviewNotification && (
          <div className="bg-stone-900 text-stone-100 text-[13px] px-4 py-2.5 flex items-center justify-between shrink-0 animate-in slide-in-from-top duration-300 z-40 border-b border-stone-850">
            <span className="flex items-center gap-1.5 font-medium select-none text-[12.5px]">
              <span className="animate-pulse">🪄</span> 
              已自动为您生成 {autoGeneratedReviewNotification.date} 的回顾
            </span>
            <div className="flex items-center gap-2">
              <button 
                onClick={() => {
                  navigate(`/review?date=${autoGeneratedReviewNotification.date}`);
                  clearAutoGeneratedReviewNotification();
                }}
                className="bg-white text-black px-2.5 py-1 rounded-md text-[11px] font-semibold hover:bg-stone-200 transition-colors"
              >
                查看
              </button>
              <button 
                onClick={clearAutoGeneratedReviewNotification}
                className="p-1 text-stone-400 hover:text-stone-200 transition-colors"
              >
                <X className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        )}

        {/* Main Canvas */}
        <main className="flex-1 overflow-hidden bg-white selection:bg-black selection:text-white flex flex-col relative">
          {isCopilotMode ? <Copilot /> : <Outlet />}
        </main>

        {/* Tab Bar */}
        <nav className="h-[64px] shrink-0 border-t border-baimiao-border/50 bg-white/80 backdrop-blur-md pb-safe z-50 relative">
          <div className="w-full h-full flex justify-around items-center px-2">
            <TabItem to="/" icon={<ChatCircleDots weight="regular" />} label="记录" />
            <TabItem to="/diary" icon={<Notepad weight="regular" />} label="日记" />
            <TabItem to="/review" icon={<Clock weight="regular" />} label="回顾" />
            <TabItem to="/insights" icon={<HeadCircuit weight="regular" />} label="洞察" />
          </div>
        </nav>
      </div>

      {/* About & Feedback Modal */}
      {showAboutModal && (
        <div 
          className="absolute inset-0 bg-black/40 backdrop-blur-sm z-[100] flex items-center justify-center p-6 animate-in fade-in duration-200"
          onClick={() => !isUpdating && setShowAboutModal(false)}
        >
          <div 
            className="bg-white rounded-2xl w-full max-w-[280px] p-6 shadow-2xl border border-baimiao-border flex flex-col items-center text-center animate-in zoom-in-95 duration-200 select-none"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="w-12 h-12 bg-gradient-to-br from-baimiao-mysteria to-[#2c2957] text-white rounded-xl flex items-center justify-center font-bold text-lg mb-4 shadow-md">
              白
            </div>
            <h3 className="text-[16px] font-semibold text-stone-900 mb-1">白描笔记</h3>
            <p className="text-[11px] text-stone-400 font-mono mb-4">v1.2.0</p>
            
            <div className="space-y-1.5 mb-6 text-center w-full text-stone-600 text-[13px] border-t border-b border-stone-200/40 py-4 flex flex-col items-center justify-center">
              <span className="text-stone-400 text-[11px] uppercase tracking-wider">作者</span>
              <span className="font-semibold text-stone-900 text-[14px]">Bitoky</span>
              <p className="text-[12px] text-stone-450 leading-relaxed mt-2.5 pt-2.5 border-t border-stone-200/20 w-full text-center">
                隐私优先的极简 AI 记录与反思工具
              </p>
            </div>

            <div className="flex flex-col gap-2 w-full">
              <button 
                onClick={handleForceUpdate}
                disabled={isUpdating}
                className={`w-full py-2.5 bg-gradient-to-r from-baimiao-mysteria to-[#2c2957] text-white hover:brightness-110 transition-all rounded-xl text-[13px] font-medium tracking-wide shadow-sm flex items-center justify-center gap-1.5 ${
                  isUpdating ? 'opacity-80 cursor-wait' : ''
                }`}
              >
                {isUpdating ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    正在检查更新...
                  </>
                ) : (
                  '检查更新并重载'
                )}
              </button>
              <a 
                href="https://github.com/haotianliangye/baimiaobiji/issues"
                target="_blank"
                rel="noopener noreferrer"
                onClick={(e) => isUpdating && e.preventDefault()}
                className={`w-full py-2 bg-stone-200/30 hover:bg-stone-200/60 text-stone-600 transition-colors rounded-xl text-[13px] font-medium flex items-center justify-center ${
                  isUpdating ? 'opacity-50 cursor-not-allowed pointer-events-none' : ''
                }`}
              >
                提交反馈 (Issue)
              </a>
              <button 
                onClick={() => !isUpdating && setShowAboutModal(false)}
                disabled={isUpdating}
                className={`w-full py-2 text-stone-400 hover:text-stone-600 transition-colors text-[13px] font-medium ${
                  isUpdating ? 'opacity-50 cursor-not-allowed' : ''
                }`}
              >
                关闭
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Global Search Panel */}
      {isSearchMode && (
        <div className="absolute inset-0 w-full max-w-md mx-auto left-0 right-0 bg-white z-[80] flex flex-col overflow-hidden animate-in fade-in duration-200">
          {/* Search Header */}
          <div className="flex h-[54px] shrink-0 items-center px-4 bg-gradient-to-r from-baimiao-mysteria to-[#2c2957] text-white gap-3 select-none border-b border-white/5">
            <div className="flex-1 bg-white/10 rounded-xl px-3 py-1 flex items-center gap-2 border border-white/5">
              <Search className="w-[15px] h-[15px] text-stone-400 shrink-0" />
              <input 
                type="text" 
                placeholder="搜索碎屑、日记、反思..." 
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                onKeyDown={handleKeyDown}
                className="w-full bg-transparent text-[13.5px] text-white outline-none placeholder:text-stone-400"
                autoFocus
              />
              {searchQuery && (
                <button onClick={() => setSearchQuery('')} className="p-0.5 text-stone-400 hover:text-white">
                  <X className="w-3.5 h-3.5" />
                </button>
              )}
            </div>
            <button 
              onClick={() => setSearchMode(false)}
              className="text-[13.5px] text-stone-300 hover:text-white font-medium shrink-0"
            >
              取消
            </button>
          </div>

          {/* Filters bar */}
          <div className="flex px-4 py-2 bg-white border-b border-stone-200/50 gap-2 shrink-0 overflow-x-auto no-scrollbar">
            {/* Date range filter selector */}
            <div className="relative shrink-0" ref={dateDropdownRef}>
              <button 
                onClick={() => setShowDateDropdown(!showDateDropdown)}
                className={`flex items-center gap-1.5 bg-stone-100 hover:bg-stone-200/80 text-stone-750 px-3 py-1 rounded-xl text-[12px] font-medium border border-stone-200/40 outline-none transition-colors cursor-pointer active:scale-95`}
              >
                <span>{
                  searchFilters.dateRange === '自定义'
                    ? (searchFilters.customStartDate && searchFilters.customEndDate
                        ? formatCustomDateLabel(searchFilters.customStartDate, searchFilters.customEndDate)
                        : '自定义时间'
                      )
                    : searchFilters.dateRange === '全部' ? '全部日期' : searchFilters.dateRange
                }</span>
                <ChevronDown className="w-3.5 h-3.5 text-stone-400" />
              </button>
            </div>

            {/* Module filters toggle */}
            {['record', 'diary', 'review', 'insight'].map((mod) => {
              const isSelected = searchFilters.modules.includes(mod);
              const getLabel = () => {
                if (mod === 'record') return '记录';
                if (mod === 'diary') return '日记';
                if (mod === 'review') return '回顾';
                return '洞察';
              };
              return (
                <button
                  key={mod}
                  onClick={() => {
                    let newModules = [...searchFilters.modules];
                    if (isSelected) {
                      if (newModules.length > 1) {
                        newModules = newModules.filter(m => m !== mod);
                      }
                    } else {
                      newModules.push(mod);
                    }
                    setSearchFilters({ ...searchFilters, modules: newModules });
                  }}
                  className={`px-3 py-1 rounded-xl text-[12px] font-medium border transition-all shrink-0 active:scale-95 ${
                    isSelected 
                      ? 'bg-gradient-to-r from-baimiao-mysteria to-[#2c2957] text-white border-transparent shadow-sm shadow-baimiao-mysteria/10' 
                      : 'bg-[#f0edf4]/50 text-[#8a859e] border-stone-200/20 hover:bg-[#f0edf4]'
                  }`}
                >
                  {getLabel()}
                </button>
              );
            })}
          </div>



          {/* Semantic Status Bar */}
          {embedEnabled && semanticSearchEnabled && (
            <div className="px-4 py-1.5 bg-[#f6f4f9] border-b border-stone-250/20 text-[11px] text-[#8a859e] flex items-center justify-between shrink-0 select-none animate-in slide-in-from-top duration-200">
              <span className="flex items-center gap-1.5">
                <span className={`w-1.5 h-1.5 rounded-full ${embeddingQueueSize > 0 ? 'bg-amber-500 animate-pulse' : totalVectorsCount > 0 ? 'bg-emerald-500' : 'bg-stone-400'}`}></span>
                {embeddingQueueSize > 0 
                  ? `本地向量生成中 (剩余 ${embeddingQueueSize} 条，已就绪 ${totalVectorsCount} 条)` 
                  : totalVectorsCount > 0 
                    ? `本地向量库已就绪 (共 ${totalVectorsCount} 条记录)` 
                    : '本地向量库为空 (请确认设置并等待数据录入)'
                }
              </span>
              {embeddingQueueSize > 0 && (
                <span className="text-[10px] text-amber-600 font-medium">正在计算中...</span>
              )}
            </div>
          )}

          {/* Date range filter dropdown card (rendered outside overflow-x-auto bar to avoid clipping) */}
          {showDateDropdown && (
            <div
              ref={dropdownCardRef}
              className="absolute left-4 top-[100px] w-60 bg-white border border-stone-200 rounded-2xl shadow-[0_8px_32px_rgba(0,0,0,0.12)] flex flex-col p-1.5 animate-in fade-in zoom-in-95 duration-100 z-[90]"
            >
              {calendarTarget === 'none' ? (
                <>
                  {/* 标准时间范围选项 */}
                  {['全部', '本周', '本月', '本季度'].map((range) => (
                    <button
                      key={range}
                      onClick={() => {
                        setSearchFilters({ 
                          ...searchFilters, 
                          dateRange: range,
                          customStartDate: '',
                          customEndDate: ''
                        });
                        setShowDateDropdown(false);
                      }}
                      className={`px-3 py-1.5 text-[12px] font-medium rounded-xl text-left transition-colors ${
                        searchFilters.dateRange === range
                          ? 'bg-baimiao-mysteria/10 text-baimiao-mysteria'
                          : 'text-stone-600 hover:text-stone-800 hover:bg-stone-100'
                      }`}
                    >
                      {range === '全部' ? '全部日期' : range}
                    </button>
                  ))}

                  {/* 自定义时间范围 */}
                  <div className="border-t border-stone-100 my-1"></div>
                  <div className="px-3 py-1.5 flex flex-col gap-2">
                    <span className="text-[10.5px] font-semibold text-stone-400 uppercase tracking-wider">自定义时间</span>

                    <div className="flex flex-col gap-1.5">
                      <div className="flex items-center justify-between gap-2">
                        <span className="text-[11.5px] text-stone-500 shrink-0">开始时间</span>
                        <button
                          onClick={() => setCalendarTarget('start')}
                          className="bg-stone-50 border border-stone-200 text-stone-700 rounded-lg px-2 py-1 text-[11px] font-mono text-left w-32 outline-none hover:border-baimiao-mysteria/40 active:bg-stone-100 transition-colors"
                        >
                          {tempStartDate || '未选择'}
                        </button>
                      </div>
                      <div className="flex items-center justify-between gap-2">
                        <span className="text-[11.5px] text-stone-500 shrink-0">结束时间</span>
                        <button
                          onClick={() => setCalendarTarget('end')}
                          className="bg-stone-50 border border-stone-200 text-stone-700 rounded-lg px-2 py-1 text-[11px] font-mono text-left w-32 outline-none hover:border-baimiao-mysteria/40 active:bg-stone-100 transition-colors"
                        >
                          {tempEndDate || '未选择'}
                        </button>
                      </div>
                    </div>
                    
                    <button
                      onClick={() => {
                        if (!tempStartDate || !tempEndDate) {
                          alert('请选择完整的开始和结束日期');
                          return;
                        }
                        if (tempStartDate > tempEndDate) {
                          alert('开始时间不能晚于结束时间');
                          return;
                        }
                        setSearchFilters({
                          ...searchFilters,
                          dateRange: '自定义',
                          customStartDate: tempStartDate,
                          customEndDate: tempEndDate
                        });
                        setShowDateDropdown(false);
                      }}
                      disabled={!tempStartDate || !tempEndDate}
                      className="w-full mt-1.5 py-1.5 bg-gradient-to-r from-baimiao-mysteria to-[#2c2957] text-white rounded-xl text-[11.5px] font-semibold flex items-center justify-center gap-1 active:scale-[0.98] disabled:opacity-40"
                    >
                      <CalendarIcon className="w-3 h-3" />
                      确定
                    </button>
                  </div>
                </>
              ) : (
                <div className="p-1">
                  <MiniCalendar 
                    value={calendarTarget === 'start' ? tempStartDate : tempEndDate}
                    onChange={(val) => {
                      if (calendarTarget === 'start') {
                        setTempStartDate(val);
                      } else {
                        setTempEndDate(val);
                      }
                      setCalendarTarget('none');
                    }}
                    onBack={() => setCalendarTarget('none')}
                    title={calendarTarget === 'start' ? '选择开始时间' : '选择结束时间'}
                  />
                </div>
              )}
            </div>
          )}

          {/* Content area */}
          <div className="flex-1 overflow-y-auto thin-scrollbar p-4 relative">
            {/* History mode */}
            {!searchQuery && (
              <div className="space-y-4">
                <div className="flex items-center justify-between px-1 select-none">
                  <span className="text-[11px] font-semibold text-stone-400 uppercase tracking-wider">最近搜索</span>
                  {searchHistory.length > 0 && (
                    <button 
                      onClick={clearSearchHistory}
                      className="p-1 text-stone-400 hover:text-red-500 transition-colors"
                    >
                      <Trash2 className="w-[14px] h-[14px]" />
                    </button>
                  )}
                </div>
                
                {searchHistory.length === 0 ? (
                  <div className="flex flex-col items-center justify-center py-16 text-center select-none">
                    <Search className="w-8 h-8 text-stone-300 mb-2 stroke-[1.5px]" />
                    <p className="text-[12px] text-stone-400">输入关键词查找您的灵感碎片</p>
                  </div>
                ) : (
                  <div className="flex flex-wrap gap-2">
                    {searchHistory.map((item) => (
                      <button
                        key={item}
                        onClick={() => {
                          setSearchQuery(item);
                          addSearchHistory(item); // 重新置顶点击的历史词
                        }}
                        className="bg-white hover:bg-stone-200/60 active:scale-[0.98] text-stone-700 px-3 py-1.5 rounded-xl text-[13px] border border-stone-200/60 shadow-sm transition-all"
                      >
                        {item}
                      </button>
                    ))}
                  </div>
                )}
              </div>
            )}

            {/* Results mode */}
            {searchQuery && (
              <div className="space-y-3">
                {isSearching ? (
                  <div className="flex flex-col items-center justify-center py-20 text-center select-none space-y-3 animate-in fade-in duration-200">
                    <Loader2 className="w-7 h-7 text-baimiao-mysteria animate-spin stroke-[1.5px]" />
                    <p className="text-[12px] text-stone-400 font-medium">正在生成搜索向量并检索本地数据库...</p>
                  </div>
                ) : (
                  <>
                    {searchError && (
                      <div className="p-3 bg-amber-50/70 border border-amber-100/60 rounded-2xl text-[12px] text-amber-800 flex flex-col gap-0.5 animate-in fade-in duration-200">
                        <div className="font-semibold flex items-center gap-1.5 text-amber-900">
                          <span className="w-1.5 h-1.5 rounded-full bg-amber-500"></span>
                          语义搜索不可用
                        </div>
                        <div className="text-amber-800/80 leading-normal">{searchError}</div>
                        <div className="text-[10.5px] text-stone-400 mt-1">提示：当前展示为普通文本检索结果。</div>
                      </div>
                    )}

                    {searchResults.length === 0 ? (
                      <div className="text-center py-20 select-none space-y-1 animate-in fade-in duration-200">
                        <p className="text-[13px] text-stone-400 font-medium">未找到匹配的内容</p>
                        <p className="text-[11px] text-stone-300">
                          已进行{semanticSearchEnabled ? '本地向量比对与' : ''}全文文本匹配。
                        </p>
                      </div>
                    ) : (
                      searchResults.map((item) => (
                        <div
                          key={`${item.type}-${item.id}`}
                          onClick={() => handleResultClick(item)}
                          className="bg-white p-3.5 rounded-2xl border border-black/[0.03] hover:border-black/[0.08] shadow-[0_1px_3px_rgba(0,0,0,0.01)] hover:shadow-md transition-all cursor-pointer space-y-1.5 active:scale-[0.99] animate-in fade-in slide-in-from-bottom-2 duration-200"
                        >
                          <div className="flex items-center justify-between text-[11px]">
                            <span className={`px-1.5 py-0.5 rounded-md font-medium text-[10px] uppercase ${
                              item.type === 'record' ? 'bg-amber-50 text-amber-600' :
                              item.type === 'diary' ? 'bg-blue-50 text-blue-600' :
                              item.type === 'review' ? 'bg-purple-50 text-purple-600' :
                              'bg-emerald-50 text-emerald-600'
                            }`}>
                              {item.type === 'record' ? '记录' :
                               item.type === 'diary' ? '日记' :
                               item.type === 'review' ? '回顾' : '洞察'}
                            </span>
                            <span className="text-stone-400 font-mono">{item.date}</span>
                          </div>
                          
                          <h4 className="text-[13.5px] font-semibold text-stone-850 leading-snug">
                            {item.title}
                          </h4>
                          
                          <p 
                            className="text-[12.5px] text-stone-550 leading-relaxed break-all selection:bg-amber-100"
                            dangerouslySetInnerHTML={{ __html: item.highlightSnippets }}
                          />
                        </div>
                      ))
                    )}
                  </>
                )}
              </div>
            )}
          </div>

          {/* Tab Bar (inside search — tapping exits search & navigates to the section) */}
          <nav className="h-[60px] shrink-0 border-t border-baimiao-border/50 bg-white/80 backdrop-blur-md pb-safe z-50 relative">
            <div className="w-full h-full flex justify-around items-center px-2">
              <TabItem to="/" icon={<ChatCircleDots weight="regular" />} label="记录" onNavigate={() => setSearchMode(false)} />
              <TabItem to="/diary" icon={<Notepad weight="regular" />} label="日记" onNavigate={() => setSearchMode(false)} />
              <TabItem to="/review" icon={<Clock weight="regular" />} label="回顾" onNavigate={() => setSearchMode(false)} />
              <TabItem to="/insights" icon={<HeadCircuit weight="regular" />} label="洞察" onNavigate={() => setSearchMode(false)} />
            </div>
          </nav>
        </div>
      )}
    </div>
  );
}

function TabItem({ to, icon, label, disabled = false, onNavigate, activeWeight = 'fill' }: { to: string, icon: React.ReactNode, label: string, disabled?: boolean, onNavigate?: () => void, activeWeight?: 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone' }) {
  const setCopilotMode = useAppStore(state => state.setCopilotMode);
  if (disabled) {
    return (
      <div className="flex flex-col items-center justify-center p-2 opacity-30 cursor-not-allowed">
        {React.cloneElement(icon as React.ReactElement<any>, { className: 'w-5 h-5 mb-1' })}
        <span className="text-[12px] tracking-wide">{label}</span>
      </div>
    );
  }
  return (
    <NavLink
      to={to}
      onClick={() => { setCopilotMode(false); onNavigate?.(); }}
      className={({ isActive }) =>
        `relative flex flex-col items-center justify-center px-4 py-1 rounded-xl transition-all duration-200 select-none ${
          isActive
            ? 'text-baimiao-mysteria'
            : 'text-[#8a859e] hover:text-baimiao-mysteria/70 active:scale-95'
        }`
      }
    >
      {({ isActive }) => (
        <>
          <div
            className={`mb-0.5 transition-transform duration-300 ${
              isActive ? 'animate-[tabBounce_0.35s_cubic-bezier(0.34,1.56,0.64,1)_both]' : ''
            }`}
          >
            {React.cloneElement(icon as React.ReactElement<any>, {
              weight: isActive ? activeWeight : 'regular',
              className: `w-6 h-6 transition-all duration-200 ${
                isActive ? 'text-baimiao-mysteria' : 'text-current'
              } ${isActive && activeWeight !== 'fill' ? 'stroke-[0.15px]' : ''}`,
            })}
          </div>
          <span
            className={`text-[11.5px] tracking-wider transition-all duration-200 ${
              isActive ? 'font-semibold' : 'font-medium'
            }`}
          >
            {label}</span>
        </>
      )}
    </NavLink>
  );
}
