import React, { useState, useEffect, useRef } from 'react';
import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { Book, Clock, Edit3, Loader2, PieChart, Settings as SettingsIcon, X, Search, Trash2, ChevronDown, Cloud, CloudOff, CloudLightning } from 'lucide-react';
import { subDays, startOfDay, endOfDay, format } from 'date-fns';
import { db } from '../db/db';
import { useAppStore } from '../store/app.store';
import { useSettingsStore } from '../store/settings.store';
import MiniCalendar from './MiniCalendar';

export default function Layout() {
  const navigate = useNavigate();
  const [showAboutModal, setShowAboutModal] = useState(false);
  const [isUpdating, setIsUpdating] = useState(false);

  const { 
    autoGeneratedNotification, 
    clearAutoGeneratedNotification, 
    silentlyGenerateDiary,
    silentlyGenerateReview,
    isSearchMode,
    searchQuery,
    searchHistory,
    searchFilters,
    searchResults,
    setSearchMode,
    setSearchQuery,
    setSearchFilters,
    clearSearchHistory,
    addSearchHistory,
    syncStatus,
    syncErrorMessage,
    syncNow
  } = useAppStore();

  const { syncEnabled } = useSettingsStore();

  const [showDateDropdown, setShowDateDropdown] = useState(false);
  const dateDropdownRef = useRef<HTMLDivElement>(null);
  const dropdownCardRef = useRef<HTMLDivElement>(null);

  const [tempStartDate, setTempStartDate] = useState(searchFilters.customStartDate || '');
  const [tempEndDate, setTempEndDate] = useState(searchFilters.customEndDate || '');
  const [calendarTarget, setCalendarTarget] = useState<'none' | 'start' | 'end'>('none');

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      const clickedBtn = dateDropdownRef.current && dateDropdownRef.current.contains(event.target as Node);
      const clickedCard = dropdownCardRef.current && dropdownCardRef.current.contains(event.target as Node);
      if (!clickedBtn && !clickedCard) {
        setShowDateDropdown(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, []);

  // Global Keyboard Shortcuts (Ctrl + Shift + S -> Sync Now)
  useEffect(() => {
    const handleGlobalShortcuts = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.shiftKey && e.key.toLowerCase() === 's') {
        e.preventDefault();
        const settings = useSettingsStore.getState();
        if (settings.syncEnabled) {
          syncNow();
          alert("已通过快捷键触发云同步对齐！");
        } else {
          alert("云同步未启用，请先前往设置进行配置。");
        }
      }
    };
    window.addEventListener('keydown', handleGlobalShortcuts);
    return () => {
      window.removeEventListener('keydown', handleGlobalShortcuts);
    };
  }, [syncNow]);

  useEffect(() => {
    if (showDateDropdown) {
      setTempStartDate(searchFilters.customStartDate || '');
      setTempEndDate(searchFilters.customEndDate || '');
    }
    setCalendarTarget('none');
  }, [showDateDropdown, searchFilters.customStartDate, searchFilters.customEndDate]);

  const formatCustomDateLabel = (start: string, end: string) => {
    try {
      const s = start.slice(5); // "MM-DD"
      const e = end.slice(5); // "MM-DD"
      return `${s} ~ ${e}`;
    } catch (err) {
      return '自定义';
    }
  };

  const handleResultClick = (item: any) => {
    if (searchQuery.trim()) {
      addSearchHistory(searchQuery);
    }
    setSearchMode(false);
    if (item.type === 'record') {
      navigate(`/?date=${item.date}`);
    } else if (item.type === 'diary') {
      navigate(`/diary?date=${item.date}`);
    } else if (item.type === 'review') {
      navigate(`/review?date=${item.date}`);
    } else if (item.type === 'insight') {
      // 洞察页不需要日期，直接导航到洞察大板块
      navigate('/insights');
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' && searchQuery.trim()) {
      addSearchHistory(searchQuery);
      (e.target as HTMLInputElement).blur(); // 收起键盘
    }
  };

  useEffect(() => {
    const checkAndAutoGenerate = async () => {
      try {
        const yesterday = subDays(new Date(), 1);
        const yesterdayStr = format(yesterday, 'yyyy-MM-dd');
        const start = startOfDay(yesterday).getTime();
        const end = endOfDay(yesterday).getTime();

        // 1. 检查昨天是否有碎屑 logs 记录
        const logs = await db.raw_logs
          .where('created_at')
          .between(start, end)
          .toArray();

        if (logs.length === 0) return;

        // 2. 并行检查日记和回顾是否已生成
        const [existingDiary, existingReview] = await Promise.all([
          db.daily_diaries.where('diary_date').equals(yesterdayStr).first(),
          db.daily_reviews.where('review_date').equals(yesterdayStr).first(),
        ]);

        // 3. 并行静默生成缺失的日记和回顾
        const tasks: Promise<void>[] = [];
        if (!existingDiary) {
          tasks.push(silentlyGenerateDiary(yesterdayStr, logs));
        }
        if (!existingReview) {
          tasks.push(silentlyGenerateReview(yesterdayStr, logs));
        }
        await Promise.all(tasks);
      } catch (err) {
        console.error("Auto generation check error:", err);
      }
    };

    const checkAndAutoSync = async () => {
      const settings = useSettingsStore.getState();
      if (settings.syncEnabled && settings.syncAutoStartup) {
        try {
          await syncNow();
        } catch (e) {
          console.error("Auto sync on startup failed:", e);
        }
      }
    };

    checkAndAutoGenerate();
    checkAndAutoSync();
  }, []);

  const handleForceUpdate = async () => {
    setIsUpdating(true);
    await new Promise(resolve => setTimeout(resolve, 100)); // 留 100ms 缓冲让 loading 样式顺畅渲染
    try {
      if ('serviceWorker' in navigator) {
        const registrations = await navigator.serviceWorker.getRegistrations();
        for (let registration of registrations) {
          await registration.update(); // 强制 Service Worker 检查并拉取最新资源
        }
      }
      // 强制 500ms 垫底延时以防动画瞬间闪过，建立良好的升级心智预期
      await new Promise(resolve => setTimeout(resolve, 500));
      window.location.reload();
    } catch (err) {
      await new Promise(resolve => setTimeout(resolve, 500));
      window.location.reload();
    }
  };

  return (
    <div className="flex flex-col h-full bg-stone-100 font-sans text-stone-900 overflow-hidden items-center justify-center">
      <div className="w-full max-w-md h-full bg-[#f4f4f0] shadow-sm ring-1 ring-black/5 flex flex-col relative overflow-hidden">
        {/* Global Nav */}
        <header className="flex h-[54px] shrink-0 items-center justify-between px-4 bg-black text-white">
          <h1 
            onClick={() => setShowAboutModal(true)} 
            className="text-[17px] font-bold tracking-wide cursor-pointer hover:opacity-80 transition-opacity active:scale-[0.98] select-none"
          >
            白描笔记
          </h1>
          <div className="flex items-center gap-1.5">
            {syncEnabled && (
              <button 
                onClick={() => syncNow()}
                disabled={syncStatus === 'syncing'}
                title={syncStatus === 'error' ? `同步出错: ${syncErrorMessage}` : '点击手动同步'}
                className="p-1.5 hover:opacity-70 transition-opacity active:scale-95 disabled:opacity-80 shrink-0"
              >
                {syncStatus === 'syncing' && <Loader2 className="w-[18px] h-[18px] text-blue-400 animate-spin" />}
                {syncStatus === 'idle' && <Cloud className="w-[18px] h-[18px] text-emerald-400 fill-emerald-500/10" />}
                {syncStatus === 'error' && <CloudLightning className="w-[18px] h-[18px] text-red-400 animate-bounce" />}
                {syncStatus === 'disabled' && <CloudOff className="w-[18px] h-[18px] text-stone-500" />}
              </button>
            )}
            <button 
              onClick={() => setSearchMode(true)} 
              className="p-1.5 hover:opacity-70 transition-opacity active:scale-95"
            >
              <Search className="w-[18px] h-[18px]" />
            </button>
            <button 
              onClick={() => navigate('/settings')} 
              className="p-1.5 hover:opacity-70 transition-opacity -mr-1.5 active:scale-95"
            >
              <SettingsIcon className="w-[18px] h-[18px]" />
            </button>
          </div>
        </header>

        {/* Global Auto-Generated Notification Toast */}
        {autoGeneratedNotification && (
          <div className="bg-stone-900 text-stone-100 text-[13px] px-4 py-2.5 flex items-center justify-between shrink-0 animate-in slide-in-from-top duration-300 z-40 border-b border-stone-850">
            <span className="flex items-center gap-1.5 font-medium select-none text-[12.5px]">
              <span className="animate-pulse">🪄</span> 
              已自动为您整理昨天的日记
            </span>
            <div className="flex items-center gap-2">
              <button 
                onClick={() => {
                  navigate(`/diary?date=${autoGeneratedNotification.date}`);
                  clearAutoGeneratedNotification();
                }}
                className="bg-white text-black px-2.5 py-1 rounded-md text-[11px] font-semibold hover:bg-stone-200 transition-colors"
              >
                查看
              </button>
              <button 
                onClick={clearAutoGeneratedNotification}
                className="p-1 text-stone-400 hover:text-stone-200 transition-colors"
              >
                <X className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        )}

        {/* Main Canvas */}
        <main className="flex-1 overflow-hidden bg-[#f4f4f0] selection:bg-black selection:text-white flex flex-col relative">
          <Outlet />
        </main>

        {/* Tab Bar */}
        <nav className="h-[60px] shrink-0 border-t border-stone-200/60 bg-[#f4f4f0]/90 backdrop-blur pb-safe z-50 relative">
          <div className="w-full h-full flex justify-around items-center px-2">
            <TabItem to="/" icon={<Edit3 />} label="记录" />
            <TabItem to="/diary" icon={<Book />} label="日记" />
            <TabItem to="/review" icon={<Clock />} label="回顾" />
            <TabItem to="/insights" icon={<PieChart />} label="洞察" />
          </div>
        </nav>
      </div>

      {/* About & Feedback Modal */}
      {showAboutModal && (
        <div 
          className="absolute inset-0 bg-black/40 backdrop-blur-sm z-[100] flex items-center justify-center p-6 animate-in fade-in duration-200"
          onClick={() => !isUpdating && setShowAboutModal(false)}
        >
          <div 
            className="bg-[#f4f4f0] rounded-2xl w-full max-w-[280px] p-6 shadow-2xl border border-stone-200/30 flex flex-col items-center text-center animate-in zoom-in-95 duration-200 select-none"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="w-12 h-12 bg-black text-white rounded-xl flex items-center justify-center font-bold text-lg mb-4 shadow-md">
              白
            </div>
            <h3 className="text-[16px] font-semibold text-stone-900 mb-1">白描笔记</h3>
            <p className="text-[11px] text-stone-400 font-mono mb-4">v1.2.0</p>
            
            <div className="space-y-1.5 mb-6 text-center w-full text-stone-600 text-[13px] border-t border-b border-stone-200/40 py-4 flex flex-col items-center justify-center">
              <span className="text-stone-400 text-[11px] uppercase tracking-wider">作者</span>
              <span className="font-semibold text-stone-900 text-[14px]">Bitoky</span>
              <p className="text-[12px] text-stone-450 leading-relaxed mt-2.5 pt-2.5 border-t border-stone-200/20 w-full text-center">
                隐私优先的极简 AI 记录与反思工具
              </p>
            </div>

            <div className="flex flex-col gap-2 w-full">
              <button 
                onClick={handleForceUpdate}
                disabled={isUpdating}
                className={`w-full py-2.5 bg-black text-white hover:bg-stone-900 transition-colors rounded-xl text-[13px] font-medium tracking-wide shadow-sm flex items-center justify-center gap-1.5 ${
                  isUpdating ? 'opacity-80 cursor-wait' : ''
                }`}
              >
                {isUpdating ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    正在检查更新...
                  </>
                ) : (
                  '检查更新并重载'
                )}
              </button>
              <a 
                href="https://github.com/haotianliangye/baimiaobiji/issues"
                target="_blank"
                rel="noopener noreferrer"
                onClick={(e) => isUpdating && e.preventDefault()}
                className={`w-full py-2 bg-stone-200/30 hover:bg-stone-200/60 text-stone-600 transition-colors rounded-xl text-[13px] font-medium flex items-center justify-center ${
                  isUpdating ? 'opacity-50 cursor-not-allowed pointer-events-none' : ''
                }`}
              >
                提交反馈 (Issue)
              </a>
              <button 
                onClick={() => !isUpdating && setShowAboutModal(false)}
                disabled={isUpdating}
                className={`w-full py-2 text-stone-400 hover:text-stone-600 transition-colors text-[13px] font-medium ${
                  isUpdating ? 'opacity-50 cursor-not-allowed' : ''
                }`}
              >
                关闭
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Global Search Panel */}
      {isSearchMode && (
        <div className="absolute inset-0 w-full max-w-md mx-auto left-0 right-0 bg-[#f4f4f0] z-[80] flex flex-col overflow-hidden animate-in fade-in duration-200">
          {/* Search Header */}
          <div className="flex h-[54px] shrink-0 items-center px-4 bg-black text-white gap-3 select-none">
            <div className="flex-1 bg-white/10 rounded-xl px-3 py-1 flex items-center gap-2 border border-white/5">
              <Search className="w-[15px] h-[15px] text-stone-400 shrink-0" />
              <input 
                type="text" 
                placeholder="搜索碎屑、日记、反思..." 
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                onKeyDown={handleKeyDown}
                className="w-full bg-transparent text-[13.5px] text-white outline-none placeholder:text-stone-400"
                autoFocus
              />
              {searchQuery && (
                <button onClick={() => setSearchQuery('')} className="p-0.5 text-stone-400 hover:text-white">
                  <X className="w-3.5 h-3.5" />
                </button>
              )}
            </div>
            <button 
              onClick={() => setSearchMode(false)}
              className="text-[13.5px] text-stone-300 hover:text-white font-medium shrink-0"
            >
              取消
            </button>
          </div>

          {/* Filters bar */}
          <div className="flex px-4 py-2 bg-white border-b border-stone-200/50 gap-2 shrink-0 overflow-x-auto no-scrollbar">
            {/* Date range filter selector */}
            <div className="relative shrink-0" ref={dateDropdownRef}>
              <button 
                onClick={() => setShowDateDropdown(!showDateDropdown)}
                className={`flex items-center gap-1.5 bg-stone-100 hover:bg-stone-200/80 text-stone-750 px-3 py-1 rounded-xl text-[12px] font-medium border border-stone-200/40 outline-none transition-colors cursor-pointer active:scale-95`}
              >
                <span>{
                  searchFilters.dateRange === '自定义'
                    ? (searchFilters.customStartDate && searchFilters.customEndDate
                        ? formatCustomDateLabel(searchFilters.customStartDate, searchFilters.customEndDate)
                        : '自定义时间'
                      )
                    : searchFilters.dateRange === '全部' ? '全部日期' : searchFilters.dateRange
                }</span>
                <ChevronDown className="w-3.5 h-3.5 text-stone-400" />
              </button>
            </div>

            {/* Module filters toggle */}
            {['record', 'diary', 'review', 'insight'].map((mod) => {
              const isSelected = searchFilters.modules.includes(mod);
              const getLabel = () => {
                if (mod === 'record') return '记录';
                if (mod === 'diary') return '日记';
                if (mod === 'review') return '回顾';
                return '洞察';
              };
              return (
                <button
                  key={mod}
                  onClick={() => {
                    let newModules = [...searchFilters.modules];
                    if (isSelected) {
                      if (newModules.length > 1) {
                        newModules = newModules.filter(m => m !== mod);
                      }
                    } else {
                      newModules.push(mod);
                    }
                    setSearchFilters({ ...searchFilters, modules: newModules });
                  }}
                  className={`px-3 py-1 rounded-xl text-[12px] font-medium border transition-colors shrink-0 ${
                    isSelected 
                      ? 'bg-black text-white border-black' 
                      : 'bg-stone-100 text-stone-600 border-stone-200/40 hover:bg-stone-200/80'
                  }`}
                >
                  {getLabel()}
                </button>
              );
            })}
          </div>

          {/* Date range filter dropdown card (rendered outside overflow-x-auto bar to avoid clipping) */}
          {showDateDropdown && (
            <div 
              ref={dropdownCardRef}
              className="absolute left-4 top-[100px] w-60 bg-[#2a2a2a]/95 backdrop-blur-xl rounded-2xl shadow-[0_10px_40px_rgba(0,0,0,0.15)] border border-white/5 flex flex-col p-1.5 animate-in fade-in zoom-in-95 duration-100 z-[90]"
            >
              {calendarTarget === 'none' ? (
                <>
                  {/* 标准时间范围选项 */}
                  {['全部', '本周', '本月', '本季度'].map((range) => (
                    <button
                      key={range}
                      onClick={() => {
                        setSearchFilters({ 
                          ...searchFilters, 
                          dateRange: range,
                          customStartDate: '',
                          customEndDate: ''
                        });
                        setShowDateDropdown(false);
                      }}
                      className={`px-3 py-1.5 text-[12px] font-medium rounded-xl text-left transition-colors ${
                        searchFilters.dateRange === range
                          ? 'bg-white/10 text-white'
                          : 'text-white/75 hover:text-white hover:bg-white/5'
                      }`}
                    >
                      {range === '全部' ? '全部日期' : range}
                    </button>
                  ))}
                  
                  {/* 自定义时间范围 */}
                  <div className="border-t border-white/10 my-1"></div>
                  <div className="px-3 py-1.5 flex flex-col gap-2">
                    <span className="text-[10.5px] font-semibold text-white/40 uppercase tracking-wider">自定义时间</span>
                    
                    <div className="flex flex-col gap-1.5">
                      <div className="flex items-center justify-between gap-2">
                        <span className="text-[11.5px] text-white/60 shrink-0">开始时间</span>
                        <button
                          onClick={() => setCalendarTarget('start')}
                          className="bg-white/5 border border-white/10 text-white rounded-lg px-2 py-1 text-[11px] font-mono text-left w-32 outline-none hover:border-white/20 active:bg-white/10 transition-colors"
                        >
                          {tempStartDate || '未选择'}
                        </button>
                      </div>
                      <div className="flex items-center justify-between gap-2">
                        <span className="text-[11.5px] text-white/60 shrink-0">结束时间</span>
                        <button
                          onClick={() => setCalendarTarget('end')}
                          className="bg-white/5 border border-white/10 text-white rounded-lg px-2 py-1 text-[11px] font-mono text-left w-32 outline-none hover:border-white/20 active:bg-white/10 transition-colors"
                        >
                          {tempEndDate || '未选择'}
                        </button>
                      </div>
                    </div>
                    
                    <button
                      onClick={() => {
                        if (!tempStartDate || !tempEndDate) {
                          alert('请选择完整的开始和结束日期');
                          return;
                        }
                        if (tempStartDate > tempEndDate) {
                          alert('开始时间不能晚于结束时间');
                          return;
                        }
                        setSearchFilters({
                          ...searchFilters,
                          dateRange: '自定义',
                          customStartDate: tempStartDate,
                          customEndDate: tempEndDate
                        });
                        setShowDateDropdown(false);
                      }}
                      className="w-full mt-1.5 py-1.5 bg-white text-black hover:bg-stone-200 transition-colors rounded-xl text-[11px] font-semibold flex items-center justify-center gap-1 active:scale-[0.98]"
                    >
                      确定
                    </button>
                  </div>
                </>
              ) : (
                <div className="p-1">
                  <MiniCalendar 
                    value={calendarTarget === 'start' ? tempStartDate : tempEndDate}
                    onChange={(val) => {
                      if (calendarTarget === 'start') {
                        setTempStartDate(val);
                      } else {
                        setTempEndDate(val);
                      }
                      setCalendarTarget('none');
                    }}
                    onBack={() => setCalendarTarget('none')}
                    title={calendarTarget === 'start' ? '选择开始时间' : '选择结束时间'}
                  />
                </div>
              )}
            </div>
          )}

          {/* Content area */}
          <div className="flex-1 overflow-y-auto thin-scrollbar p-4 relative">
            {/* History mode */}
            {!searchQuery && (
              <div className="space-y-4">
                <div className="flex items-center justify-between px-1 select-none">
                  <span className="text-[11px] font-semibold text-stone-400 uppercase tracking-wider">最近搜索</span>
                  {searchHistory.length > 0 && (
                    <button 
                      onClick={clearSearchHistory}
                      className="p-1 text-stone-400 hover:text-red-500 transition-colors"
                    >
                      <Trash2 className="w-[14px] h-[14px]" />
                    </button>
                  )}
                </div>
                
                {searchHistory.length === 0 ? (
                  <div className="flex flex-col items-center justify-center py-16 text-center select-none">
                    <Search className="w-8 h-8 text-stone-300 mb-2 stroke-[1.5px]" />
                    <p className="text-[12px] text-stone-400">输入关键词查找您的灵感碎片</p>
                  </div>
                ) : (
                  <div className="flex flex-wrap gap-2">
                    {searchHistory.map((item) => (
                      <button
                        key={item}
                        onClick={() => {
                          setSearchQuery(item);
                          addSearchHistory(item); // 重新置顶点击的历史词
                        }}
                        className="bg-white hover:bg-stone-200/60 active:scale-[0.98] text-stone-700 px-3 py-1.5 rounded-xl text-[13px] border border-stone-200/60 shadow-sm transition-all"
                      >
                        {item}
                      </button>
                    ))}
                  </div>
                )}
              </div>
            )}

            {/* Results mode */}
            {searchQuery && (
              <div className="space-y-3">
                {searchResults.length === 0 ? (
                  <div className="text-center py-20 select-none">
                    <p className="text-[13px] text-stone-400">未找到匹配的内容</p>
                  </div>
                ) : (
                  searchResults.map((item) => (
                    <div
                      key={`${item.type}-${item.id}`}
                      onClick={() => handleResultClick(item)}
                      className="bg-white p-3.5 rounded-2xl border border-black/[0.03] hover:border-black/[0.08] shadow-[0_1px_3px_rgba(0,0,0,0.01)] hover:shadow-md transition-all cursor-pointer space-y-1.5 active:scale-[0.99]"
                    >
                      <div className="flex items-center justify-between text-[11px]">
                        <span className={`px-1.5 py-0.5 rounded-md font-medium text-[10px] uppercase ${
                          item.type === 'record' ? 'bg-amber-50 text-amber-600' :
                          item.type === 'diary' ? 'bg-blue-50 text-blue-600' :
                          item.type === 'review' ? 'bg-purple-50 text-purple-600' :
                          'bg-emerald-50 text-emerald-600'
                        }`}>
                          {item.type === 'record' ? '记录' :
                           item.type === 'diary' ? '日记' :
                           item.type === 'review' ? '回顾' : '洞察'}
                        </span>
                        <span className="text-stone-400 font-mono">{item.date}</span>
                      </div>
                      
                      <h4 className="text-[13.5px] font-semibold text-stone-850 leading-snug">
                        {item.title}
                      </h4>
                      
                      <p 
                        className="text-[12.5px] text-stone-550 leading-relaxed break-all selection:bg-amber-100"
                        dangerouslySetInnerHTML={{ __html: item.highlightSnippets }}
                      />
                    </div>
                  ))
                )}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

function TabItem({ to, icon, label, disabled = false }: { to: string, icon: React.ReactNode, label: string, disabled?: boolean }) {
  if (disabled) {
    return (
      <div className="flex flex-col items-center justify-center p-2 opacity-30 cursor-not-allowed">
        {React.cloneElement(icon as React.ReactElement<any>, { className: 'w-5 h-5 mb-1' })}
        <span className="text-[12px] tracking-wide">{label}</span>
      </div>
    );
  }
  return (
    <NavLink
      to={to}
      className={({ isActive }) =>
        `flex flex-col items-center justify-center p-2 transition-colors duration-200 ${
          isActive ? 'text-black' : 'text-stone-400 hover:text-stone-600'
        }`
      }
    >
      {({ isActive }) => (
        <>
          {React.cloneElement(icon as React.ReactElement<any>, {
            className: `w-5 h-5 mb-1 ${isActive ? 'stroke-[2.5px]' : 'stroke-2'}`,
          })}
          <span className={`text-[12px] tracking-wide ${isActive ? 'font-medium' : ''}`}>{label}</span>
        </>
      )}
    </NavLink>
  );
}
