import React, { useState, useEffect, useRef } from 'react';
import { NavLink, Outlet, useNavigate, useLocation, useSearchParams } from 'react-router-dom';
import { Loader2, X, Search, Trash2, ChevronDown, Cloud, CloudOff, CloudLightning, Sparkles, MessageSquare, Calendar as CalendarIcon, Menu, Lightbulb, ChevronLeft, ChevronRight } from 'lucide-react';
import { ChatCircleDots, HeadCircuit, Clock, Sun } from '@phosphor-icons/react';
import { subDays, format, parse, addDays, isSameDay } from 'date-fns';
import { useAppStore } from '../store/app.store';
import { useSettingsStore } from '../store/settings.store';
import MiniCalendar from './MiniCalendar';
import CalendarHeatmap from './CalendarHeatmap';
import RandomWalk from './RandomWalk';
import Copilot from '../pages/Copilot';
import { useTranslation } from '../lib/i18n';

export default function Layout() {
  const navigate = useNavigate();
  const { t } = useTranslation();

  const {
    autoGeneratedNotification, 
    clearAutoGeneratedNotification, 
    autoGeneratedReviewNotification,
    clearAutoGeneratedReviewNotification,
    autoGenTasks,
    isProcessingQueue,
    isQueuePaused,
    checkAndGenerateHistoryTasks,
    isSearchMode,
    searchQuery,
    searchHistory,
    searchFilters,
    searchResults,
    setSearchMode,
    setSearchQuery,
    setSearchFilters,
    clearSearchHistory,
    addSearchHistory,
    syncStatus,
    syncErrorMessage,
    syncNow,
    semanticSearchEnabled,
    setSemanticSearchEnabled,
    isSearching,
    searchError,
    totalVectorsCount,
    embeddingQueueSize,
    isCopilotMode,
    setCopilotMode,
    isRandomWalkMode,
    setRandomWalkMode,
    thoughtsViewMode,
    setThoughtsViewMode,
    mingwuTimeRange,
    setMingwuTimeRange,
  } = useAppStore();

  const { syncEnabled, embedEnabled, diaryPrompts } = useSettingsStore();

  // --- Seam 1：统一顶部标题栏 ---
  const location = useLocation();
  const [searchParams, setSearchParams] = useSearchParams();
  const currentPath = location.pathname;
  // 日期导航仅在「拾微 / 回顾」两个按日期浏览的 Tab 显示
  const showDateNav = currentPath === '/' || currentPath === '/review';
  // 需求 6：沉淀中间为瀑布流/时间线胶囊；洞察中间为时间范围胶囊
  const showThoughtsCapsule = currentPath === '/thoughts';
  const showMingwuCapsule = currentPath === '/mingwu';

  // 页面标题映射：拾微=白描 / 回顾 / 沉淀 / 洞察（标题不可点击）
  const routeTitleKey: Record<string, string> = {
    '/': 'layout.titleBaimiao',
    '/review': 'tab.review',
    '/thoughts': 'tab.thoughts',
    '/mingwu': 'tab.mingwu',
  };
  const headerTitleKey = routeTitleKey[currentPath] || 'layout.titleBaimiao';

  // 需求 6：洞察时间范围胶囊选项（复用现有洞察下拉选项与语义）
  const mingwuRangeOptions = [
    { value: 'day', label: t('mingwu.rangeDay') },
    { value: 'week', label: t('mingwu.rangeWeek') },
    { value: 'month', label: t('mingwu.rangeMonth') },
    { value: 'quarter', label: t('mingwu.rangeQuarter') },
    { value: 'half-year', label: t('mingwu.rangeHalfYear') },
    { value: 'year', label: t('mingwu.rangeYear') },
    { value: 'custom', label: t('mingwu.rangeCustomRange') },
  ];
  const mingwuRangeLabel = (range: string) =>
    mingwuRangeOptions.find((o) => o.value === range)?.label || t('mingwu.rangeWeek');

  // 日期导航（与各页面共用 ?date= 查询参数）
  const [showDatePicker, setShowDatePicker] = useState(false);
  const navToday = new Date();
  const dateParam = searchParams.get('date');
  let targetDate = navToday;
  if (dateParam) {
    const parsed = parse(dateParam, 'yyyy-MM-dd', new Date());
    if (!isNaN(parsed.getTime())) targetDate = parsed;
  }
  const dateStr = format(targetDate, 'yyyy-MM-dd');
  // 需求 6：日期选择器仅显示月-日（字号比标题略小）
  const dateDisplayStr = format(targetDate, 'MM-dd');
  const isTodayDate = isSameDay(targetDate, navToday);
  const navigateToDate = (offset: number) => {
    const newDate = offset > 0 ? addDays(targetDate, offset) : subDays(targetDate, Math.abs(offset));
    setSearchParams({ date: format(newDate, 'yyyy-MM-dd') });
  };
  const heatmapSection = currentPath === '/review' ? 'review' : 'record';

  // 灯泡入口：随机漫步（全局状态控制显隐，主内容区渲染）

  const [showDateDropdown, setShowDateDropdown] = useState(false);
  const dateDropdownRef = useRef<HTMLDivElement>(null);
  const dropdownCardRef = useRef<HTMLDivElement>(null);
  const [showPromptDropdown, setShowPromptDropdown] = useState(false);
  const promptDropdownRef = useRef<HTMLDivElement>(null);
  const promptCardRef = useRef<HTMLDivElement>(null);
  const [promptCardPos, setPromptCardPos] = useState<{ top: number; left: number } | null>(null);

  // 需求 6：沉淀胶囊 & 洞察时间范围胶囊下拉
  const [showThoughtsDropdown, setShowThoughtsDropdown] = useState(false);
  const thoughtsCapsuleRef = useRef<HTMLDivElement>(null);
  const thoughtsCardRef = useRef<HTMLDivElement>(null);
  const [showMingwuDropdown, setShowMingwuDropdown] = useState(false);
  const mingwuCapsuleRef = useRef<HTMLDivElement>(null);
  const mingwuCardRef = useRef<HTMLDivElement>(null);

  const [tempStartDate, setTempStartDate] = useState(searchFilters.customStartDate || '');
  const [tempEndDate, setTempEndDate] = useState(searchFilters.customEndDate || '');
  const [calendarTarget, setCalendarTarget] = useState<'none' | 'start' | 'end'>('none');

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      const clickedBtn = dateDropdownRef.current && dateDropdownRef.current.contains(event.target as Node);
      const clickedCard = dropdownCardRef.current && dropdownCardRef.current.contains(event.target as Node);
      if (!clickedBtn && !clickedCard) {
        setShowDateDropdown(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, []);

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      const inButton = promptDropdownRef.current && promptDropdownRef.current.contains(event.target as Node);
      const inCard = promptCardRef.current && promptCardRef.current.contains(event.target as Node);
      if (!inButton && !inCard) {
        setShowPromptDropdown(false);
        setPromptCardPos(null);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, []);

  // 需求 6：沉淀胶囊点击外部关闭
  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      const inButton = thoughtsCapsuleRef.current && thoughtsCapsuleRef.current.contains(event.target as Node);
      const inCard = thoughtsCardRef.current && thoughtsCardRef.current.contains(event.target as Node);
      if (!inButton && !inCard) {
        setShowThoughtsDropdown(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, []);

  // 需求 6：洞察时间范围胶囊点击外部关闭
  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      const inButton = mingwuCapsuleRef.current && mingwuCapsuleRef.current.contains(event.target as Node);
      const inCard = mingwuCardRef.current && mingwuCardRef.current.contains(event.target as Node);
      if (!inButton && !inCard) {
        setShowMingwuDropdown(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, []);

  useEffect(() => {
    if (showDateDropdown) {
      setTempStartDate(searchFilters.customStartDate || '');
      setTempEndDate(searchFilters.customEndDate || '');
    }
    setCalendarTarget('none');
  }, [showDateDropdown, searchFilters.customStartDate, searchFilters.customEndDate]);

  const formatCustomDateLabel = (start: string, end: string) => {
    try {
      const s = start.slice(5); // "MM-DD"
      const e = end.slice(5); // "MM-DD"
      return `${s} ~ ${e}`;
    } catch (err) {
      return t('search.custom');
    }
  };

  // #12: dateRange 内部仍用中文串作标识符（app.store 过滤逻辑依赖），仅显示时映射到 i18n
  const dateRangeDisplayKey: Record<string, string> = {
    '全部': 'search.allDates',
    '本周': 'search.thisWeek',
    '本月': 'search.thisMonth',
    '本季度': 'search.thisQuarter',
    '自定义': 'search.custom',
  };
  const dateRangeLabel = (range: string) => t(dateRangeDisplayKey[range] || 'search.custom');

  const handleResultClick = (item: any) => {
    if (searchQuery.trim()) {
      addSearchHistory(searchQuery);
    }
    setSearchMode(false);
    if (item.type === 'record') {
      navigate(`/?date=${item.date}`);
    } else if (item.type === 'diary') {
      navigate(`/review?date=${item.date}`);
    } else if (item.type === 'review') {
      navigate(`/review?date=${item.date}`);
    } else if (item.type === 'insight') {
      // 洞察页不需要日期，直接导航到洞察大板块
      navigate('/mingwu');
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' && searchQuery.trim()) {
      addSearchHistory(searchQuery);
      (e.target as HTMLInputElement).blur(); // 收起键盘
    }
  };

  useEffect(() => {
    checkAndGenerateHistoryTasks(7);
  }, []);

  const togglePromptDropdown = () => {
    // Measure the button position so the dropdown card (rendered outside the
    // overflow-x-auto filter row to avoid clipping) can anchor to it.
    if (!showPromptDropdown && promptDropdownRef.current) {
      const r = promptDropdownRef.current.getBoundingClientRect();
      setPromptCardPos({ top: r.bottom + 4, left: r.left });
    }
    setShowPromptDropdown(!showPromptDropdown);
    setShowDateDropdown(false);
  };

  return (
    <div className="flex flex-col h-full bg-[#f0eef5] font-sans text-stone-900 overflow-hidden items-center justify-center">
      <div className="w-full max-w-md h-full bg-white shadow-sm ring-1 ring-black/5 flex flex-col relative overflow-hidden">
        {/* Global Nav —— Seam 1 统一顶部栏：左 [≡]标题·副标题 / 中 <日期> / 右 搜索->RAG+CHAT->灯泡 */}
        {!isCopilotMode && (
          <header className="relative flex h-[54px] shrink-0 items-center justify-between px-3 bg-gradient-to-r from-baimiao-mysteria to-[#2c2957] text-white/95 border-b border-white/5">
            {/* 左：[≡] 页面标题 · 副标题（标题不可点击，≡ 进设置） */}
            <div className="flex items-center gap-2 min-w-0 flex-1 z-10">
              {/*
                G2: 随机漫步模式下隐藏 [≡] 设置入口。
                需求 102 规定退出方式仅 灯泡/×/Tab 三种，[≡] 既非退出入口
                又会 navigate('/settings') 但不重置 isRandomWalkMode，导致
                URL 变 /settings 而界面仍渲染 RandomWalk、设置抽屉不可达。
              */}
              {!isRandomWalkMode && (
                <button
                  onClick={() => navigate('/settings', { state: { drawer: true } })}
                  title={t('settings.title')}
                  aria-label={t('settings.title')}
                  className="p-1.5 hover:opacity-70 transition-opacity active:scale-95 shrink-0"
                >
                  <Menu className="w-[18px] h-[18px]" />
                </button>
              )}
              <h1 className="text-[16px] font-normal font-serif tracking-widest select-none truncate translate-y-[2px]">
                {isRandomWalkMode ? t('randomWalk.title') : t(headerTitleKey)}
              </h1>
              {isRandomWalkMode ? null : (
                autoGenTasks.length > 0 && (isProcessingQueue || isQueuePaused) ? (
                  <span className={`flex items-center gap-1 bg-white/10 text-white/90 border border-white/10 text-[10px] px-2 py-0.5 rounded-full font-medium select-none tracking-wide ${isQueuePaused ? 'opacity-65' : 'animate-pulse'} shrink-0`}>
                    <Loader2 className={`w-2.5 h-2.5 text-white/60 ${isQueuePaused ? '' : 'animate-spin'}`} />
                    {isQueuePaused ? `${t('layout.aiPaused')} (${autoGenTasks.length})` : `${t('layout.aiProcessing')} (${autoGenTasks.length})`}
                  </span>
                ) : null
              )}
            </div>

            {/* 中：日期导航（仅拾微/回顾；点击日期打开日期选择器；随机漫步模式下隐藏） */}
            {showDateNav && !isRandomWalkMode && (
              <div className="absolute left-1/2 -translate-x-1/2 flex items-center gap-1 shrink-0 z-20">
                <button
                  onClick={() => navigateToDate(-1)}
                  aria-label={t('layout.prevDay')}
                  title={t('layout.prevDay')}
                  className="p-1 hover:opacity-70 transition-opacity active:scale-95"
                >
                  <ChevronLeft className="w-4 h-4" />
                </button>
                <button
                  onClick={() => setShowDatePicker(true)}
                  aria-label={t('layout.selectDate')}
                  title={t('layout.selectDate')}
                  className="text-[12px] font-mono text-white/90 w-[56px] text-center select-none hover:opacity-80 py-1 rounded-md transition-opacity active:scale-95"
                >
                  {dateDisplayStr}
                </button>
                <button
                  onClick={() => navigateToDate(1)}
                  disabled={isTodayDate}
                  aria-label={t('layout.nextDay')}
                  title={t('layout.nextDay')}
                  className="p-1 hover:opacity-70 transition-opacity active:scale-95 disabled:opacity-30 disabled:hover:opacity-30"
                >
                  <ChevronRight className="w-4 h-4" />
                </button>
              </div>
            )}

            {/* 中：沉淀瀑布流/时间线下拉胶囊切换器（仅文字无图标；随机漫步模式下隐藏） */}
            {showThoughtsCapsule && !isRandomWalkMode && (
              <div className="absolute left-1/2 -translate-x-1/2 shrink-0 z-20" ref={thoughtsCapsuleRef}>
                <button
                  onClick={() => setShowThoughtsDropdown(!showThoughtsDropdown)}
                  className="px-3 py-1 rounded-full bg-white/10 border border-white/10 text-white/90 text-[12px] font-medium select-none hover:bg-white/15 transition-colors active:scale-95"
                >
                  {thoughtsViewMode === 'masonry' ? t('thoughts.masonry') : t('thoughts.timeline')}
                </button>
              </div>
            )}
            {showThoughtsCapsule && showThoughtsDropdown && (
              <div
                ref={thoughtsCardRef}
                className="absolute left-1/2 -translate-x-1/2 top-[44px] z-50 bg-white rounded-xl shadow-[0_8px_32px_rgba(0,0,0,0.12)] flex flex-col p-1 animate-in fade-in zoom-in-95 duration-100"
              >
                <button
                  data-testid="view-masonry"
                  onClick={() => { setThoughtsViewMode('masonry'); setShowThoughtsDropdown(false); }}
                  className={`px-4 py-1.5 text-[12px] font-medium rounded-lg text-left transition-colors ${
                    thoughtsViewMode === 'masonry'
                      ? 'bg-baimiao-mysteria/10 text-baimiao-mysteria'
                      : 'text-stone-600 hover:text-stone-800 hover:bg-stone-100'
                  }`}
                >
                  {t('thoughts.masonry')}
                </button>
                <button
                  data-testid="view-timeline"
                  onClick={() => { setThoughtsViewMode('timeline'); setShowThoughtsDropdown(false); }}
                  className={`px-4 py-1.5 text-[12px] font-medium rounded-lg text-left transition-colors ${
                    thoughtsViewMode === 'timeline'
                      ? 'bg-baimiao-mysteria/10 text-baimiao-mysteria'
                      : 'text-stone-600 hover:text-stone-800 hover:bg-stone-100'
                  }`}
                >
                  {t('thoughts.timeline')}
                </button>
              </div>
            )}

            {/* 中：洞察时间范围下拉胶囊（随机漫步模式下隐藏） */}
            {showMingwuCapsule && !isRandomWalkMode && (
              <div className="absolute left-1/2 -translate-x-1/2 shrink-0 z-20" ref={mingwuCapsuleRef}>
                <button
                  data-testid="mingwu-range-dropdown"
                  onClick={() => setShowMingwuDropdown(!showMingwuDropdown)}
                  className="flex items-center gap-1 px-3 py-1 rounded-full bg-white/10 border border-white/10 text-white/90 text-[12px] font-medium select-none hover:bg-white/15 transition-colors active:scale-95"
                >
                  {mingwuRangeLabel(mingwuTimeRange)}
                  <ChevronDown className="w-3 h-3 opacity-60" />
                </button>
              </div>
            )}
            {showMingwuCapsule && showMingwuDropdown && (
              <div
                ref={mingwuCardRef}
                className="absolute left-1/2 -translate-x-1/2 top-[44px] z-50 bg-gradient-to-r from-baimiao-mysteria/95 to-[#2c2957]/95 backdrop-blur-xl rounded-xl shadow-[0_8px_32px_rgba(0,0,0,0.15)] p-1.5 animate-in fade-in zoom-in-95 duration-100 w-[200px]"
              >
                <div className="grid grid-cols-4 gap-1">
                  {mingwuRangeOptions.map((opt) => (
                    <button
                      key={opt.value}
                      data-testid={`mingwu-range-option-${opt.value}`}
                      onClick={() => { setMingwuTimeRange(opt.value); setShowMingwuDropdown(false); }}
                      className={`px-1 py-2 text-[11px] font-medium rounded-lg text-center transition-colors ${
                        mingwuTimeRange === opt.value
                          ? 'bg-white/15 text-white'
                          : 'text-white/70 hover:text-white hover:bg-white/10'
                      }`}
                    >
                      {opt.label}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* 右：随机漫步模式下只显示×关闭；否则显示 同步/搜索/RAG/灯泡入口 */}
            <div className="flex items-center gap-2 shrink-0 flex-1 justify-end z-10">
              {isRandomWalkMode ? (
                <button
                  data-testid="walk-close"
                  onClick={() => setRandomWalkMode(false)}
                  title={t('about.close')}
                  aria-label={t('about.close')}
                  className="p-1.5 hover:opacity-70 transition-opacity active:scale-95 shrink-0"
                >
                  <X className="w-[18px] h-[18px]" />
                </button>
              ) : (
                <>
                  {syncEnabled && (
                    <button
                      onClick={() => syncNow()}
                      disabled={syncStatus === 'syncing'}
                      title={syncStatus === 'error' ? `${t('layout.syncError')}: ${syncErrorMessage}` : t('layout.syncManual')}
                      aria-label={syncStatus === 'error' ? `${t('layout.syncError')}: ${syncErrorMessage}` : t('layout.syncManual')}
                      className="p-1.5 hover:opacity-70 transition-opacity active:scale-95 disabled:opacity-80 shrink-0"
                    >
                      {syncStatus === 'syncing' && <Loader2 className="w-[18px] h-[18px] text-blue-400 animate-spin" />}
                      {syncStatus === 'idle' && <Cloud className="w-[18px] h-[18px] text-emerald-400 fill-emerald-500/10" />}
                      {syncStatus === 'error' && <CloudLightning className="w-[18px] h-[18px] text-red-400 animate-bounce" />}
                      {syncStatus === 'disabled' && <CloudOff className="w-[18px] h-[18px] text-stone-500" />}
                    </button>
                  )}
                  <button
                    onClick={() => setSearchMode(true)}
                    aria-label={t('search.placeholder')}
                    className="p-1.5 hover:opacity-70 transition-opacity active:scale-95"
                  >
                    <Search className="w-[18px] h-[18px]" />
                  </button>
                  <button
                    onClick={() => setCopilotMode(true)}
                    title={t('layout.copilot')}
                    aria-label={t('layout.copilot')}
                    className="p-1.5 hover:opacity-70 transition-opacity active:scale-95"
                  >
                    <MessageSquare className="w-[18px] h-[18px]" />
                  </button>
                  <button
                    data-testid="walk-open"
                    onClick={() => setRandomWalkMode(true)}
                    title={t('thoughts.randomWalk')}
                    aria-label={t('thoughts.randomWalk')}
                    className="p-1.5 hover:opacity-70 transition-opacity active:scale-95"
                  >
                    <Lightbulb className="w-[18px] h-[18px]" />
                  </button>
                </>
              )}
            </div>
          </header>
        )}

        {/* Global Auto-Generated Notification Toast */}
        {autoGeneratedNotification && (
          <div className="bg-stone-900 text-stone-100 text-[13px] px-4 py-2.5 flex items-center justify-between shrink-0 animate-in slide-in-from-top duration-300 z-40 border-b border-stone-850">
            <span className="flex items-center gap-1.5 font-medium select-none text-[12.5px]">
              <span className="animate-pulse">🪄</span>
              {t('notify.autoDiary', { date: autoGeneratedNotification.date })}
            </span>
            <div className="flex items-center gap-2">
              <button
                onClick={() => {
                  navigate(`/review?date=${autoGeneratedNotification.date}`);
                  clearAutoGeneratedNotification();
                }}
                className="bg-white text-black px-2.5 py-1 rounded-md text-[11px] font-semibold hover:bg-stone-200 transition-colors"
              >
                {t('notify.view')}
              </button>
              <button 
                onClick={clearAutoGeneratedNotification}
                className="p-1 text-stone-400 hover:text-stone-200 transition-colors"
              >
                <X className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        )}

        {autoGeneratedReviewNotification && (
          <div className="bg-stone-900 text-stone-100 text-[13px] px-4 py-2.5 flex items-center justify-between shrink-0 animate-in slide-in-from-top duration-300 z-40 border-b border-stone-850">
            <span className="flex items-center gap-1.5 font-medium select-none text-[12.5px]">
              <span className="animate-pulse">🪄</span>
              {t('notify.autoReview', { date: autoGeneratedReviewNotification.date })}
            </span>
            <div className="flex items-center gap-2">
              <button
                onClick={() => {
                  navigate(`/review?date=${autoGeneratedReviewNotification.date}`);
                  clearAutoGeneratedReviewNotification();
                }}
                className="bg-white text-black px-2.5 py-1 rounded-md text-[11px] font-semibold hover:bg-stone-200 transition-colors"
              >
                {t('notify.view')}
              </button>
              <button
                onClick={clearAutoGeneratedReviewNotification}
                className="p-1 text-stone-400 hover:text-stone-200 transition-colors"
              >
                <X className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        )}

        {/* Main Canvas */}
        <main className="flex-1 overflow-hidden bg-white selection:bg-black selection:text-white flex flex-col relative">
          {isCopilotMode ? <Copilot /> : isRandomWalkMode ? <RandomWalk /> : <Outlet />}
        </main>

        {/* Tab Bar */}
        <nav className="h-[64px] shrink-0 border-t border-baimiao-border/50 bg-white/80 backdrop-blur-md pb-safe z-50 relative">
          <div className="w-full h-full flex justify-around items-center px-2">
            <TabItem to="/" end icon={<ChatCircleDots weight="regular" />} label={t('tab.record')} />
            <TabItem to="/review" icon={<Clock weight="regular" />} label={t('tab.review')} />
            <TabItem to="/thoughts" icon={<HeadCircuit weight="regular" />} label={t('tab.thoughts')} />
            <TabItem to="/mingwu" icon={<Sun weight="regular" />} label={t('tab.mingwu')} />
          </div>
        </nav>
      </div>

      {/* 日期选择器（顶部栏中间日期入口）-- 统计+热力图模块（CalendarHeatmap） */}
      {showDatePicker && (
        <CalendarHeatmap
          currentDate={targetDate}
          onSelectDate={(date) => { setSearchParams({ date }); setShowDatePicker(false); }}
          onClose={() => setShowDatePicker(false)}
          activeSection={heatmapSection}
        />
      )}

      {/* Global Search Panel */}
      {isSearchMode && (
        <div className="absolute inset-0 w-full max-w-md mx-auto left-0 right-0 bg-white z-[80] flex flex-col overflow-hidden animate-in fade-in duration-200">
          {/* Search Header */}
          <div className="flex h-[54px] shrink-0 items-center px-4 bg-gradient-to-r from-baimiao-mysteria to-[#2c2957] text-white gap-3 select-none border-b border-white/5">
            <div className="flex-1 bg-white/10 rounded-xl px-3 py-1 flex items-center gap-2 border border-white/5">
              <Search className="w-[15px] h-[15px] text-stone-400 shrink-0" />
              <input
                type="text"
                placeholder={t('search.placeholder')}
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                onKeyDown={handleKeyDown}
                className="w-full bg-transparent text-[13.5px] text-white outline-none placeholder:text-stone-400"
                autoFocus
              />
              {searchQuery && (
                <button onClick={() => setSearchQuery('')} className="p-0.5 text-stone-400 hover:text-white">
                  <X className="w-3.5 h-3.5" />
                </button>
              )}
            </div>
            <button 
              onClick={() => setSearchMode(false)}
              className="text-[13.5px] text-stone-300 hover:text-white font-medium shrink-0"
            >
              {t('search.cancel')}
            </button>
          </div>

          {/* Filters bar */}
          <div className="flex px-4 py-2 bg-white border-b border-stone-200/50 gap-2 shrink-0 overflow-x-auto no-scrollbar">
            {/* Date range filter selector */}
            <div className="relative shrink-0" ref={dateDropdownRef}>
              <button 
                onClick={() => setShowDateDropdown(!showDateDropdown)}
                className={`flex items-center gap-1.5 bg-stone-100 hover:bg-stone-200/80 text-stone-750 px-3 py-1 rounded-xl text-[12px] font-medium border border-stone-200/40 outline-none transition-colors cursor-pointer active:scale-95`}
              >
                <span>{
                  searchFilters.dateRange === '自定义'
                    ? (searchFilters.customStartDate && searchFilters.customEndDate
                        ? formatCustomDateLabel(searchFilters.customStartDate, searchFilters.customEndDate)
                        : t('search.customTime')
                      )
                    : dateRangeLabel(searchFilters.dateRange)
                }</span>
                <ChevronDown className="w-3.5 h-3.5 text-stone-400" />
              </button>
            </div>

            {/* Module filters toggle */}
            {['record', 'diary', 'review', 'insight'].map((mod) => {
              const isSelected = searchFilters.modules.includes(mod);
              const getLabel = () => {
                if (mod === 'record') return t('search.typeRecord');
                if (mod === 'diary') return t('search.typeDiary');
                if (mod === 'review') return t('search.typeReview');
                return t('search.typeInsight');
              };
              return (
                <button
                  key={mod}
                  onClick={() => {
                    let newModules = [...searchFilters.modules];
                    if (isSelected) {
                      if (newModules.length > 1) {
                        newModules = newModules.filter(m => m !== mod);
                      }
                    } else {
                      newModules.push(mod);
                    }
                    setSearchFilters({ ...searchFilters, modules: newModules });
                  }}
                  className={`px-3 py-1 rounded-xl text-[12px] font-medium border transition-all shrink-0 active:scale-95 ${
                    isSelected 
                      ? 'bg-gradient-to-r from-baimiao-mysteria to-[#2c2957] text-white border-transparent shadow-sm shadow-baimiao-mysteria/10' 
                      : 'bg-[#f0edf4]/50 text-[#8a859e] border-stone-200/20 hover:bg-[#f0edf4]'
                  }`}
                >
                  {getLabel()}
                </button>
              );
            })}
          </div>



          {/* Semantic Status Bar */}
          {embedEnabled && semanticSearchEnabled && (
            <div className="px-4 py-1.5 bg-[#f6f4f9] border-b border-stone-250/20 text-[11px] text-[#8a859e] flex items-center justify-between shrink-0 select-none animate-in slide-in-from-top duration-200">
              <span className="flex items-center gap-1.5">
                <span className={`w-1.5 h-1.5 rounded-full ${embeddingQueueSize > 0 ? 'bg-amber-500 animate-pulse' : totalVectorsCount > 0 ? 'bg-emerald-500' : 'bg-stone-400'}`}></span>
                {embeddingQueueSize > 0
                  ? t('search.vectorGenerating', { queue: embeddingQueueSize, ready: totalVectorsCount })
                  : totalVectorsCount > 0
                    ? t('search.vectorReady', { count: totalVectorsCount })
                    : t('search.vectorEmpty')
                }
              </span>
              {embeddingQueueSize > 0 && (
                <span className="text-[10px] text-amber-600 font-medium">{t('search.computing')}</span>
              )}
            </div>
          )}

          {/* Date range filter dropdown card (rendered outside overflow-x-auto bar to avoid clipping) */}
          {showDateDropdown && (
            <div
              ref={dropdownCardRef}
              className="absolute left-4 top-[100px] w-60 bg-white border border-stone-200 rounded-2xl shadow-[0_8px_32px_rgba(0,0,0,0.12)] flex flex-col p-1.5 animate-in fade-in zoom-in-95 duration-100 z-[90]"
            >
              {calendarTarget === 'none' ? (
                <>
                  {/* 标准时间范围选项 */}
                  {['全部', '本周', '本月', '本季度'].map((range) => (
                    <button
                      key={range}
                      onClick={() => {
                        setSearchFilters({
                          ...searchFilters,
                          dateRange: range,
                          customStartDate: '',
                          customEndDate: ''
                        });
                        setShowDateDropdown(false);
                      }}
                      className={`px-3 py-1.5 text-[12px] font-medium rounded-xl text-left transition-colors ${
                        searchFilters.dateRange === range
                          ? 'bg-baimiao-mysteria/10 text-baimiao-mysteria'
                          : 'text-stone-600 hover:text-stone-800 hover:bg-stone-100'
                      }`}
                    >
                      {dateRangeLabel(range)}
                    </button>
                  ))}

                  {/* 自定义时间范围 */}
                  <div className="border-t border-stone-100 my-1"></div>
                  <div className="px-3 py-1.5 flex flex-col gap-2">
                    <span className="text-[10.5px] font-semibold text-stone-400 uppercase tracking-wider">{t('search.customTime')}</span>

                    <div className="flex flex-col gap-1.5">
                      <div className="flex items-center justify-between gap-2">
                        <span className="text-[11.5px] text-stone-500 shrink-0">{t('search.startDate')}</span>
                        <button
                          onClick={() => setCalendarTarget('start')}
                          className="bg-stone-50 border border-stone-200 text-stone-700 rounded-lg px-2 py-1 text-[11px] font-mono text-left w-32 outline-none hover:border-baimiao-mysteria/40 active:bg-stone-100 transition-colors"
                        >
                          {tempStartDate || t('search.notSelected')}
                        </button>
                      </div>
                      <div className="flex items-center justify-between gap-2">
                        <span className="text-[11.5px] text-stone-500 shrink-0">{t('search.endDate')}</span>
                        <button
                          onClick={() => setCalendarTarget('end')}
                          className="bg-stone-50 border border-stone-200 text-stone-700 rounded-lg px-2 py-1 text-[11px] font-mono text-left w-32 outline-none hover:border-baimiao-mysteria/40 active:bg-stone-100 transition-colors"
                        >
                          {tempEndDate || t('search.notSelected')}
                        </button>
                      </div>
                    </div>

                    <button
                      onClick={() => {
                        if (!tempStartDate || !tempEndDate) {
                          alert(t('search.alertSelectDates'));
                          return;
                        }
                        if (tempStartDate > tempEndDate) {
                          alert(t('search.alertStartAfterEnd'));
                          return;
                        }
                        setSearchFilters({
                          ...searchFilters,
                          dateRange: '自定义',
                          customStartDate: tempStartDate,
                          customEndDate: tempEndDate
                        });
                        setShowDateDropdown(false);
                      }}
                      disabled={!tempStartDate || !tempEndDate}
                      className="w-full mt-1.5 py-1.5 bg-gradient-to-r from-baimiao-mysteria to-[#2c2957] text-white rounded-xl text-[11.5px] font-semibold flex items-center justify-center gap-1 active:scale-[0.98] disabled:opacity-40"
                    >
                      <CalendarIcon className="w-3 h-3" />
                      {t('search.confirm')}
                    </button>
                  </div>
                </>
              ) : (
                <div className="p-1">
                  <MiniCalendar 
                    value={calendarTarget === 'start' ? tempStartDate : tempEndDate}
                    onChange={(val) => {
                      if (calendarTarget === 'start') {
                        setTempStartDate(val);
                      } else {
                        setTempEndDate(val);
                      }
                      setCalendarTarget('none');
                    }}
                    onBack={() => setCalendarTarget('none')}
                    title={calendarTarget === 'start' ? t('search.selectStart') : t('search.selectEnd')}
                  />
                </div>
              )}
            </div>
          )}

          {/* Content area */}
          <div className="flex-1 overflow-y-auto thin-scrollbar p-4 relative">
            {/* History mode */}
            {!searchQuery && (
              <div className="space-y-4">
                <div className="flex items-center justify-between px-1 select-none">
                  <span className="text-[11px] font-semibold text-stone-400 uppercase tracking-wider">{t('search.recent')}</span>
                  {searchHistory.length > 0 && (
                    <button 
                      onClick={clearSearchHistory}
                      className="p-1 text-stone-400 hover:text-red-500 transition-colors"
                    >
                      <Trash2 className="w-[14px] h-[14px]" />
                    </button>
                  )}
                </div>
                
                {searchHistory.length === 0 ? (
                  <div className="flex flex-col items-center justify-center py-16 text-center select-none">
                    <Search className="w-8 h-8 text-stone-300 mb-2 stroke-[1.5px]" />
                    <p className="text-[12px] text-stone-400">{t('search.emptyHint')}</p>
                  </div>
                ) : (
                  <div className="flex flex-wrap gap-2">
                    {searchHistory.map((item) => (
                      <button
                        key={item}
                        onClick={() => {
                          setSearchQuery(item);
                          addSearchHistory(item); // 重新置顶点击的历史词
                        }}
                        className="bg-white hover:bg-stone-200/60 active:scale-[0.98] text-stone-700 px-3 py-1.5 rounded-xl text-[13px] border border-stone-200/60 shadow-sm transition-all"
                      >
                        {item}
                      </button>
                    ))}
                  </div>
                )}
              </div>
            )}

            {/* Results mode */}
            {searchQuery && (
              <div className="space-y-3">
                {isSearching ? (
                  <div className="flex flex-col items-center justify-center py-20 text-center select-none space-y-3 animate-in fade-in duration-200">
                    <Loader2 className="w-7 h-7 text-baimiao-mysteria animate-spin stroke-[1.5px]" />
                    <p className="text-[12px] text-stone-400 font-medium">{t('search.searching')}</p>
                  </div>
                ) : (
                  <>
                    {searchError && (
                      <div className="p-3 bg-amber-50/70 border border-amber-100/60 rounded-2xl text-[12px] text-amber-800 flex flex-col gap-0.5 animate-in fade-in duration-200">
                        <div className="font-semibold flex items-center gap-1.5 text-amber-900">
                          <span className="w-1.5 h-1.5 rounded-full bg-amber-500"></span>
                          {t('search.semanticUnavailable')}
                        </div>
                        <div className="text-amber-800/80 leading-normal">{searchError}</div>
                        <div className="text-[10.5px] text-stone-400 mt-1">{t('search.semanticHint')}</div>
                      </div>
                    )}

                    {searchResults.length === 0 ? (
                      <div className="text-center py-20 select-none space-y-1 animate-in fade-in duration-200">
                        <p className="text-[13px] text-stone-400 font-medium">{t('search.noResults')}</p>
                        <p className="text-[11px] text-stone-300">
                          {t('search.searchedVia', { via: semanticSearchEnabled ? t('search.viaSemantic') : '' })}
                        </p>
                      </div>
                    ) : (
                      searchResults.map((item) => (
                        <div
                          key={`${item.type}-${item.id}`}
                          onClick={() => handleResultClick(item)}
                          className="bg-white p-3.5 rounded-2xl border border-black/[0.03] hover:border-black/[0.08] shadow-[0_1px_3px_rgba(0,0,0,0.01)] hover:shadow-md transition-all cursor-pointer space-y-1.5 active:scale-[0.99] animate-in fade-in slide-in-from-bottom-2 duration-200"
                        >
                          <div className="flex items-center justify-between text-[11px]">
                            <span className={`px-1.5 py-0.5 rounded-md font-medium text-[10px] uppercase ${
                              item.type === 'record' ? 'bg-amber-50 text-amber-600' :
                              item.type === 'diary' ? 'bg-blue-50 text-blue-600' :
                              item.type === 'review' ? 'bg-purple-50 text-purple-600' :
                              'bg-emerald-50 text-emerald-600'
                            }`}>
                              {item.type === 'record' ? t('search.typeRecord') :
                               item.type === 'diary' ? t('search.typeDiary') :
                               item.type === 'review' ? t('search.typeReview') : t('search.typeInsight')}
                            </span>
                            <span className="text-stone-400 font-mono">{item.date}</span>
                          </div>
                          
                          <h4 className="text-[13.5px] font-semibold text-stone-850 leading-snug">
                            {item.title}
                          </h4>
                          
                          <p 
                            className="text-[12.5px] text-stone-550 leading-relaxed break-all selection:bg-amber-100"
                            dangerouslySetInnerHTML={{ __html: item.highlightSnippets }}
                          />
                        </div>
                      ))
                    )}
                  </>
                )}
              </div>
            )}
          </div>

          {/* Tab Bar (inside search — tapping exits search & navigates to the section) */}
          <nav className="h-[60px] shrink-0 border-t border-baimiao-border/50 bg-white/80 backdrop-blur-md pb-safe z-50 relative">
            <div className="w-full h-full flex justify-around items-center px-2">
              <TabItem to="/" end icon={<ChatCircleDots weight="regular" />} label={t('tab.record')} onNavigate={() => setSearchMode(false)} />
              <TabItem to="/review" icon={<Clock weight="regular" />} label={t('tab.review')} onNavigate={() => setSearchMode(false)} />
              <TabItem to="/thoughts" icon={<HeadCircuit weight="regular" />} label={t('tab.thoughts')} onNavigate={() => setSearchMode(false)} />
              <TabItem to="/mingwu" icon={<Sun weight="regular" />} label={t('tab.mingwu')} onNavigate={() => setSearchMode(false)} />
            </div>
          </nav>
        </div>
      )}
    </div>
  );
}

function TabItem({ to, icon, label, disabled = false, onNavigate, activeWeight = 'fill', end = false }: { to: string, icon: React.ReactNode, label: string, disabled?: boolean, onNavigate?: () => void, activeWeight?: 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone', end?: boolean }) {
  const setCopilotMode = useAppStore(state => state.setCopilotMode);
  const setRandomWalkMode = useAppStore(state => state.setRandomWalkMode);
  if (disabled) {
    return (
      <div className="flex flex-col items-center justify-center p-2 opacity-30 cursor-not-allowed">
        {React.cloneElement(icon as React.ReactElement<any>, { className: 'w-5 h-5 mb-1' })}
        <span className="text-[12px] tracking-wide">{label}</span>
      </div>
    );
  }
  return (
    <NavLink
      to={to}
      end={end}
      onClick={() => { setCopilotMode(false); setRandomWalkMode(false); onNavigate?.(); }}
      className={({ isActive }) =>
        `relative flex flex-col items-center justify-center px-4 py-1 rounded-xl transition-all duration-200 select-none ${
          isActive
            ? 'text-baimiao-mysteria'
            : 'text-[#8a859e] hover:text-baimiao-mysteria/70 active:scale-95'
        }`
      }
    >
      {({ isActive }) => (
        <>
          <div
            className={`mb-0.5 transition-transform duration-300 ${
              isActive ? 'animate-[tabBounce_0.35s_cubic-bezier(0.34,1.56,0.64,1)_both]' : ''
            }`}
          >
            {React.cloneElement(icon as React.ReactElement<any>, {
              weight: isActive ? activeWeight : 'regular',
              className: `w-6 h-6 transition-all duration-200 ${
                isActive ? 'text-baimiao-mysteria' : 'text-current'
              } ${isActive && activeWeight !== 'fill' ? 'stroke-[0.15px]' : ''}`,
            })}
          </div>
          <span
            className={`text-[11.5px] tracking-wider transition-all duration-200 ${
              isActive ? 'font-semibold' : 'font-medium'
            }`}
          >
            {label}</span>
        </>
      )}
    </NavLink>
  );
}
